import type { ArticleData } from "@/lib/articleLibrary";

const additions: Record<string, string> = {
  "First Home": "This is where we get practical. We can compare lenders, deposit pathways, repayments and the purchase range side by side, then turn that into a short list of actions. If a credit limit is holding you back, we show you the impact. If a government pathway could help, we check the current eligibility. If the purchase range is close but not quite there, we can test another lender, a different deposit or a different timeline. You do not need to solve all of this yourself before calling. Bring us the rough idea and we will help turn it into a plan you can actually use at inspections and auctions.",
  Upgrading: "Our job is to put the moving pieces on one page. We can model the current home, the next home, equity, repayments, sell-first, buy-first and bridging options and show you what each pathway looks like. If you want to keep the existing home, we can model that too. The point is not to tell you to play it safe. It is to give you enough clarity to make a bigger move confidently. Once the numbers are visible, we can usually identify where there is room to improve the structure, preserve cash or use a different lender to create a better result.",
  Investment: "We approach investment lending as a sequence, not a single approval. We can calculate usable equity, compare borrowing capacity across lenders, model repayments, review lender order and show you what the position could look like after settlement. If the first version does not create enough room for the next property, we can test the levers: purchase price, deposit, lender, loan structure, credit limits or timing. That is the advantage of doing the work before the contract. You are not locked into one answer. You can see the pathways and choose the one that best supports the portfolio you are trying to build.",
  "Regional & Rural": "This is where specialist property knowledge makes the process easier. Send us the listing and we can work through the land size, zoning, improvements, access and intended use, then match those characteristics with lenders that are comfortable with the security. If one lender does not like the property, that does not mean the property cannot be financed. It may simply mean we need a different policy fit. We can also model valuation scenarios and deposit options so you know what room you have. The goal is to help you chase the lifestyle property with a finance path already forming behind it.",
  Business: "Business-owner lending gives us more levers than a standard PAYG application. We can review company profit, wages, distributions, depreciation, one-off costs, current trading and entity structure, then compare lenders that treat those inputs differently. If the latest completed financial year does not reflect where the business is now, we can look at whether another evidence pathway is available. The opportunity is often in presenting the business properly and choosing the right credit policy. You built the business; our job is to translate that strength into a lending position that helps you build the next thing outside it as well.",
  Refinancing: "We can turn the refinance into a proper comparison rather than a rate-shopping exercise. We model the current loan against realistic alternatives, including fees, remaining term, monthly cash flow, interest over time and any equity release. Then we can test what happens if you keep repayments at the old level, shorten the term or redirect savings into an offset. If the current lender can sharpen its pricing, we can factor that in too. The objective is simple: use the refinance to create a measurable improvement and then decide where that improvement should go next.",
  Construction: "Construction finance gets much easier when the money plan sits beside the build plan. We can map the land, contract, extras, cash contribution, contingency and progress payments and then choose a lender that fits the project. If the valuation or timing creates a gap, we can work through the options before it becomes urgent. If the build has unusual features or a regional location, we can identify the likely lender questions early. The aim is not to slow the project down with finance. It is to get the funding structure organised so the build can keep moving.",
  Assets: "We can compare the asset-finance options in the same language you run the business in: cash out today, monthly repayment, term, balloon and cash left in the bank. From there we can test which structure gives the asset room to earn while keeping working capital available for everything else. If the asset is specialised, used or outside a standard dealer channel, we can look across specialist lenders rather than forcing it into one bank policy. The objective is to put the asset to work quickly and keep the business liquid enough to take the next opportunity as well.",
};

const fallback = "The point of the conversation is to find the lever that makes the move more achievable. We can compare lenders, structures, timing and cash-flow options and show you what changes when each lever moves. You do not need to arrive with the solution already worked out. Bring us the outcome you want, the rough numbers and the part that feels stuck. We will work through the pathways and build the finance around the opportunity rather than starting with a product and asking you to fit inside it.";

export function ensureAspirationalDepth(article: ArticleData): ArticleData {
  const wordCount = `${article.summary} ${article.sections.map(section => `${section.heading} ${section.body}`).join(" ")}`.trim().split(/\s+/).filter(Boolean).length;
  if (wordCount >= 700) return article;
  return {
    ...article,
    sections: [...article.sections, { heading: "How we help make it happen", body: additions[article.category] ?? fallback }],
  };
}

export function ensureAspirationalDepthForMany(articles: ArticleData[]): ArticleData[] {
  return articles.map(ensureAspirationalDepth);
}
