import type { ArticleData } from "@/lib/articleLibrary";

const bySlug: Record<string, Partial<ArticleData>> = {
  "buy-before-you-sell-options": {
    title: "Want to buy before you sell? Here’s how to make the move work",
    summary: "Buying the next home before selling the current one can be a smart move when the structure is built properly. The key is to map the peak debt, likely sale outcome, buffer and exit plan before you start negotiating on the new place.",
    sections: [
      { heading: "Start with what you want the move to achieve", body: "If you have found the right home before the current one is ready to sell, that does not automatically mean you have to walk away. There are usually several ways to structure the move. We start by working out what matters most: securing the next home, avoiding temporary accommodation, keeping the current property if that is part of the plan, or simply giving yourself enough time to sell properly. Once the goal is clear, we can model the finance around it. This is where good strategy earns its keep. You stop asking ‘Can I bridge?’ and start asking ‘Which structure gives me the best chance of making the move without creating unnecessary pressure?’" },
      { heading: "Work backwards from the peak debt", body: "The useful number is the maximum debt you may carry while both properties are in play. We calculate the current mortgage, new purchase, costs, expected sale proceeds and any bridging component so you can see the full position before you commit. That gives you a working range rather than a vague approval number. If the peak debt is comfortable, you have options. If it is tight, we can look at a lower purchase range, a different lender, a bigger cash contribution, an earlier sale campaign or a different settlement sequence. There is almost always more than one lever to pull." },
      { heading: "Build the sale assumptions properly", body: "The sale of the current home is the exit plan, so we make the assumptions realistic. That means allowing for agent costs, marketing, mortgage discharge and a sensible sale range rather than pretending the top appraisal is guaranteed. This is not about being negative. It is about giving you room to negotiate confidently. If the property sells strongly, great—you finish in a better position. If it takes a little longer, the plan still has breathing room. The goal is to make the strategy robust enough that you can focus on the property decision rather than watching every open home on the old place with your heart in your throat." },
      { heading: "Compare the pathways, not just the products", body: "Sell first, buy first, bridge, line up settlements, negotiate a longer settlement or use available equity. These are all tools. The right one depends on your equity, income, timing and how hard the new property will be to replace. We model the alternatives side by side so you can see what changes in repayments, debt, timing and flexibility. Sometimes bridging is the cleanest answer. Sometimes it is not. The win is knowing the pathway before the pressure arrives." },
      { heading: "Keep the next move in view", body: "A bigger home should not mean smaller future options. If you also want to invest, renovate, reduce working hours or build a business, we factor that into the structure now. That may mean preserving some equity, keeping cash in offset or choosing a lender with better future capacity. The next home matters. So does the life around it. We want the finance to support both." },
      { heading: "Your next move", body: "If you are thinking about upgrading, talk to us before you list or offer. We can model buy-first, sell-first and bridging scenarios, show you the peak and end debt, and give you a practical range to work with. Then you can look at property with a plan instead of trying to solve the finance after you have already fallen in love with the house." },
    ],
  },
  "first-investment-property-borrowing-plan": {
    title: "Your first investment property: how to set it up so property two is still possible",
    summary: "Your first investment should create momentum, not use every ounce of capacity. We can map the deposit, equity, lender sequence, repayments and buffer so the first purchase becomes the start of a bigger plan.",
    sections: [
      { heading: "Think beyond property one", body: "The first investment is exciting because it turns an idea into something real. But the best first purchase is not simply the biggest property a lender will approve. It is the one that fits your cash flow, uses equity intelligently and still leaves room for whatever comes next. We start by mapping your current home, debt, income, savings and available equity. Then we ask a different question: if this first property goes ahead, what does the position look like after settlement? That is where the strategy starts to become useful." },
      { heading: "Know whether the real limit is deposit or borrowing capacity", body: "Some buyers have plenty of equity but limited servicing. Others have strong income but not enough deposit. They are different problems and they need different solutions. We work out which constraint is actually holding the plan back, then target that. That might mean using equity from the home, changing the purchase range, reviewing unused credit limits, selecting a lender that treats income more favourably or simply sequencing the application differently. The point is to stop guessing and identify the lever that actually moves the result." },
      { heading: "Choose the lender with the second property in mind", body: "This is where a lot of investors accidentally box themselves in. The easiest lender for property one may not be the best lender to use first. Different banks assess rental income, existing debt and household commitments differently. If you want to buy again later, lender sequencing matters. We can preserve more flexible lenders for later stages and avoid concentrating every loan in one place if that limits future options. The first lender should help you get the first property and keep the bigger strategy alive." },
      { heading: "Use equity deliberately", body: "Equity can make the deposit easier, but it should have a job. We work out how much needs to be released, where that split should sit and how the additional debt affects the household. The aim is not to pull out the maximum simply because it is available. It is to use enough to make the investment happen while keeping the balance sheet strong. This is where good structuring can make a big difference to clarity and future flexibility." },
      { heading: "Keep enough cash to stay dangerous", body: "A cash buffer gives you options. Vacancy, maintenance, rate changes and opportunities are all easier to handle when you are not running the account down to the last dollar at settlement. We like investors to finish a purchase with enough liquidity to keep making good decisions. The amount depends on your position, but the principle is simple: the investment should add opportunity, not make every surprise feel like a crisis." },
      { heading: "Your next move", body: "If you are ready for your first investment, we can build the first two or three moves on paper before you buy anything. You will know your realistic purchase range, deposit or equity position, likely repayments, lender options and what capacity may remain. That gives you a much better brief than ‘What can I borrow?’ It gives you a plan for how to start." },
    ],
  },
  "borrowing-limit-or-lender-limit": {
    title: "Been told you’ve hit your borrowing limit? You may have only hit your bank’s limit",
    summary: "Borrowing capacity is not one fixed number. Different lenders can produce very different outcomes from the same income, rent and debts. The opportunity is understanding where the real constraint sits and what can be changed.",
    sections: [
      { heading: "One calculator is not the market", body: "If your current bank says you cannot borrow any more, that is one lender’s view of your position—not necessarily the end of the strategy. Lenders use different serviceability models, rent shading, buffers and income rules. That means the same household can receive materially different outcomes. Our job is to work out whether the limit is genuinely your finances or simply the way one lender is assessing them. That distinction can open up the next move." },
      { heading: "Find the actual pressure point", body: "Borrowing capacity is usually being constrained by something specific: existing debt, credit limits, HELP obligations, the way rental income is shaded, loan terms or the treatment of variable income. Once we know what is doing the damage, we can look at practical options. Sometimes closing an unused card creates enough room. Sometimes a different lender materially improves capacity. Sometimes restructuring existing debt or changing the next purchase price is the smarter move. The answer becomes much clearer when you know which input is creating the problem." },
      { heading: "Use lender policy as a strategy tool", body: "Experienced investors do not treat lender selection as a price comparison. Policy matters. Some lenders are stronger with bonuses, commissions, business income or investment debt. Others may be better later in a portfolio. We compare the rules as part of the sequence so you are not using your strongest lender too early or creating unnecessary concentration with one bank. This is one of the simplest ways to keep future options open." },
      { heading: "Improve the structure without wrecking the cash flow", body: "The goal is not to force a calculator to pass at any cost. It is to improve capacity in a way that still makes sense for the household. That might involve reducing limits, changing lenders, extending a term where appropriate, using interest-only strategically or simply waiting until an income increase is evidenced. We model the effect before recommending the change. You should be able to see what each step achieves and what it costs." },
      { heading: "Build the next property into the current decision", body: "If you are already investing, the current loan is never just about the current property. Every new debt changes the next application. We look at the order of lenders, the security structure and the likely next move before committing. That helps turn a collection of mortgages into a portfolio strategy." },
      { heading: "Your next move", body: "If you have been told you are at capacity, send us the current loans, credit limits, rents, income and the next target. We can compare lender positions and show you where the real constraint sits. The result may be a different lender, a restructure or a revised purchase range—but you will know what is possible and what needs to happen next." },
    ],
  },
  "acreage-home-loan-lender-checks": {
    title: "Want acreage? Here’s how to get the property and the finance working together",
    summary: "Acreage finance is absolutely possible. The key is matching the property characteristics with the right lender before the contract makes the decision for you.",
    sections: [
      { heading: "Acreage is a property question and a lender question", body: "If the goal is more land, a shed, room for the kids, animals or simply a different lifestyle, we start with the property you actually want—not a generic suburban policy. Acreage can be financed well when the lender understands the security. Land size, zoning, access, services, improvements and intended use all shape the lender pool. The opportunity is getting those details in front of the right lender early so the finance supports the lifestyle instead of becoming a late surprise." },
      { heading: "Send us the listing before you assume anything", body: "This is one of the easiest wins. If you find a property you like, send us the address or listing. We can look at the land, improvements and location and identify which lender questions are likely to matter. That can save a lot of wasted time. A property that one lender sees as unusual may be perfectly acceptable to another. The aim is not to avoid non-standard properties. It is to know which lenders are comfortable with them." },
      { heading: "Use the features as part of the plan", body: "Large sheds, multiple dwellings, workshops, water infrastructure and lifestyle improvements can be exactly why you want the property. They can also affect valuation and classification. We work through that upfront. If there is a business use, income-producing activity or another dwelling, we make sure the application tells the right story. The finance should reflect what the property really is, not try to squeeze it into a suburban template." },
      { heading: "Build room for the valuation", body: "Acreage valuations can vary more because comparable sales are often limited. That does not mean the deal is fragile. It means we plan the deposit and buffer with the valuation in mind. If the valuation lands where expected, great. If it is conservative, you already know the options. That gives you more confidence when negotiating and less drama close to settlement." },
      { heading: "Local knowledge helps us ask better questions", body: "Regional Victoria has plenty of perfectly financeable properties that look unusual to a lender sitting in a metro credit team. Knowing the patterns across South Gippsland, West Gippsland and Melbourne’s outer south-east helps us identify what matters quickly. We still work within lender policy, but we can get to the right questions and the right lenders faster." },
      { heading: "Your next move", body: "If acreage is on the radar, start the finance conversation while you are still looking. We can assess your borrowing range and then review specific properties as they appear. That means you can chase the lifestyle you actually want with a clearer idea of which properties and lenders fit the plan." },
    ],
  },
  "self-employed-home-loan-income-story": {
    title: "Self-employed? Here’s how we get lenders to see the business you actually built",
    summary: "Business owners often have more borrowing strength than a standard tax-return glance suggests. The key is understanding the entity structure, recurring income, add-backs and which lender policy fits the way your business really works.",
    sections: [
      { heading: "Start with the business story, not one tax-return number", body: "If you run a good business, the lending conversation should not stop at one line of taxable income. Companies, trusts and partnerships can move income in different ways. Depreciation, one-off costs, interest, retained profit and distributions can all affect the picture. We work through how the business actually earns money and then match that to lender policy. The goal is simple: give the lender a clear, credible picture of the income that is genuinely available to support the loan." },
      { heading: "Choose the lender that understands the structure", body: "Different lenders can treat the same business very differently. One may be comfortable with company profit. Another may want a longer history. Another may use current-year performance where the old financials no longer tell the story. We compare those policies before lodging anything. That can turn a frustrating ‘computer says no’ situation into a much cleaner path simply by using a lender whose rules fit the business." },
      { heading: "Use the recent numbers when the business has moved forward", body: "Businesses change. You hire staff, lose a customer, invest in equipment, win a major contract or have a year with unusual costs. If the current business is stronger than an older return suggests, we look at whether current-year trading, BAS or other evidence can help under lender policy. The aim is to use the strongest honest version of the business story—not pretend the last completed year is the only information that matters." },
      { heading: "Low-doc can be a pathway, not a compromise", body: "For the right business owner, alternative-documentation lending can be a practical way forward where up-to-date full financials are not available. Depending on the lender, BAS, bank statements or accountant evidence may be used. It is not about skipping the assessment. It is about using a different evidence path that better matches the business. We compare the pricing and trade-offs so you can decide whether that pathway is worth it." },
      { heading: "Turn business success into personal opportunity", body: "A lot of business owners build strong businesses and leave the personal balance sheet for later. A home upgrade, investment property or commercial premises can be part of turning that work into personal wealth. We look at what the business can support without starving working capital, then structure the personal lending around the bigger goal. The business should keep moving while you build outside it." },
      { heading: "Your next move", body: "If you are self-employed, bring us the structure and the latest numbers. We will work through the entities, income and lender options and tell you which path looks strongest. The goal is not to make you fit a bank. It is to find the lender and evidence path that fit the business you have actually built." },
    ],
  },
  "first-home-buyer-borrowing-power-plan": {
    title: "First home? Here’s how to turn your borrowing power into a real buying plan",
    summary: "Your first home becomes much easier once you know the purchase range, cash needed, repayments and the options available to get there. The goal is to give you a clear starting point and a path forward.",
    sections: [
      { heading: "Turn the maximum into a useful range", body: "A borrowing calculator is only the start. We work out the lender maximum, then build a range that fits the repayments and lifestyle you actually want. That gives you something practical to take to inspections and auctions. Instead of wondering whether every property is too expensive, you know the range, the monthly repayment and how much room is left after settlement." },
      { heading: "Use every deposit pathway available", body: "A first-home deposit does not always have to mean waiting until you have 20%. Depending on eligibility and current settings, government guarantees, family support, savings and lender options may all help. We compare the pathways and the costs so you can see what gets you into the market sooner and what keeps the structure strongest. The question is not ‘Do I have 20%?’ It is ‘What are the realistic ways I can buy?’" },
      { heading: "Clean up the things that hold capacity back", body: "Credit-card limits, personal loans and other commitments can reduce borrowing power. Sometimes a simple tidy-up makes a meaningful difference. We can show you what is actually affecting the result before you start cancelling everything. That lets you focus on the changes that move the number rather than making random decisions because someone on TikTok said to close every account." },
      { heading: "Use pre-approval to shop with confidence", body: "Pre-approval is useful because it gives you a range and a lender position before the emotion of buying kicks in. We still check the property once you find it, but you start the search with far more confidence. You know the likely repayments, what cash is needed and what conditions remain. That changes the whole buying experience." },
      { heading: "Set the first loan up for the next move", body: "Your first home is rarely the last property decision you will make. We look at features like offset, flexibility and lender structure in the context of what you may want next. You do not need every feature under the sun. You need a loan that does the job now and does not make the next step unnecessarily harder." },
      { heading: "Your next move", body: "If buying a first home feels confusing, start with a Game Plan. We can work out the purchase range, deposit options, repayments and lender pathways, then show you what to do next. You do not need every answer before you begin. You need a clear first move." },
    ],
  },
  "refinance-break-even-real-savings": {
    title: "Refinancing: how to turn a lower rate into a genuinely better position",
    summary: "A refinance can do more than trim the rate. Done properly, it can improve cash flow, reduce interest, shorten the loan, release equity or create a structure that fits the next move better.",
    sections: [
      { heading: "Start with what you want the refinance to improve", body: "The best refinance conversations start with the outcome. Do you want lower monthly repayments? Faster debt reduction? Better offset features? Equity for an investment or renovation? A cleaner structure? Once the goal is clear, we can compare lenders properly. A lower rate is useful, but the real win is moving into a structure that makes your overall position better." },
      { heading: "Calculate the break-even point", body: "Switching lenders has costs, so we put them on the table. Then we compare those costs with the expected monthly and interest savings. If the refinance cost is recovered quickly and the new structure fits the plan, the case becomes clear. If it takes too long, we keep looking. This is where a simple break-even calculation stops the conversation being driven by headline rates and cashback offers." },
      { heading: "Keep the term working in your favour", body: "One of the easiest ways to improve the outcome is to compare the new loan using the same remaining term as the old one. That lets you see the real interest saving. We can also show what happens if you take the lower rate and keep making the old repayment. That is often where the refinance starts to create serious momentum because more of each repayment goes toward principal." },
      { heading: "Use the restructure to create options", body: "Refinancing is a chance to clean up splits, add an offset, separate investment borrowing or release equity for a defined purpose. The structure should match what you are trying to build next. If investment or tax deductibility is involved, we coordinate with your accountant so the lending structure supports the intended outcome." },
      { heading: "Make the current lender compete", body: "Sometimes the best refinance outcome is staying where you are on better pricing. We can review the market, compare alternatives and use that information to decide whether moving lenders is worth it. The goal is not to collect a new bank logo. It is to improve your position." },
      { heading: "Your next move", body: "Send us the current loan balance, rate, repayments, term and fees. We can compare the current position with realistic alternatives and show you the cash-flow saving, interest saving and break-even point. Then you can decide whether to stay, switch or restructure with the numbers in front of you." },
    ],
  },
  "business-owner-turning-equity-into-personal-wealth": {
    title: "Business owners: how to turn a strong business into a stronger personal balance sheet",
    summary: "You built the business. The next move is using that success to create more options outside it—home, investment, commercial property and long-term personal wealth.",
    sections: [
      { heading: "Give the business a second job", body: "A strong business can do more than fund operations and income. Over time, it can become the engine behind a better home, an investment portfolio, commercial property or other assets outside the operating business. That does not mean stripping cash out. It means deliberately using the income and balance sheet you have built to create personal options as well." },
      { heading: "Keep working capital strong while you build personally", body: "You do not need to choose between a healthy business and personal wealth creation. We can compare using business cash, personal savings, equity and lending so you can see which approach preserves the most flexibility. Often the smartest structure is the one that keeps enough cash inside the business to keep taking opportunities while finance does part of the heavy lifting outside it." },
      { heading: "Make lenders understand the whole business", body: "Company profit, wages, distributions and entity structures can all form part of the lending story. We work through the numbers so the lender sees the strength of the business properly. That can open up more options than simply looking at one personal taxable-income figure. It is about presenting the business clearly and choosing a lender whose policy matches it." },
      { heading: "Use property as part of the bigger plan", body: "For some owners, the next move is a home upgrade. For others it is an investment property or commercial premises. Each one can play a different role in the personal balance sheet. We model the lending side and work alongside your accountant where tax and ownership advice is needed. The result should feel deliberate—not like another transaction squeezed in between running the business." },
      { heading: "Build before the exit", body: "You do not have to wait until you sell the business to start building outside it. Creating personal assets progressively can give you more options later and reduce the pressure on one future exit event. The idea is simple: use the years when the business is producing strongly to start building the next chapter as well." },
      { heading: "Your next move", body: "If the business is performing and you are wondering what that can unlock personally, start with the whole picture. We can assess the business income, current debts, equity and goals and show you the realistic home, investment or commercial lending options. The conversation is not ‘How much can the bank give me?’ It is ‘How do we turn the business I built into the next thing I want to build?’" },
    ],
  },
  "construction-loan-before-signing-building-contract": {
    title: "Building a home? Here’s how to get the finance lined up before the build takes over",
    summary: "Construction finance works well when the funding plan is built alongside the project. Map the total cost, cash contribution, valuation, progress payments and buffer early and the build becomes much easier to manage.",
    sections: [
      { heading: "Build the full project budget first", body: "The building contract is the centrepiece, but it is not always the whole cost. We add the land, contract, known site costs, upgrades, landscaping, connections and contingency so you can see the real funding requirement. That gives you a much stronger starting point because you know exactly what the loan needs to do and how much cash should remain available." },
      { heading: "Know how the money will flow", body: "Construction lending works through progress payments. Rather than receiving the whole loan upfront, funds are released as stages are completed. We map when your own contribution is likely to be used, how invoices are handled and what the interest position looks like while the build progresses. Once you understand the flow, the loan becomes much less mysterious." },
      { heading: "Use the buffer for the fun stuff", body: "Variations happen. The kitchen changes, the driveway costs more, or you decide the standard tiles are not coming home with you. A buffer gives you room to make those decisions without creating a funding problem later. We help you understand which costs the lender may fund and which are better kept in cash so you can make changes with your eyes open." },
      { heading: "Get the valuation working early", body: "The lender values the proposed home from the plans, specifications and contract. We want that process happening early enough that any gap can be managed before the build is locked in. If the valuation is strong, great. If it is conservative, we can look at the deposit, scope, lender or other options. The earlier we know, the more choices you have." },
      { heading: "Coordinate the land and build timing", body: "Land settlement, titles, contracts and construction approval can all move on different timelines. We map the sequence so the approval is still useful when the builder is ready to start. This is especially important with untitled land or longer build lead times. Good coordination keeps the finance in front of the project rather than chasing it." },
      { heading: "Your next move", body: "If you are planning to build, send us the land details, contract and project budget as early as you can. We can map the cash and loan position, explain progress payments and identify any lender or valuation issues before they become urgent. The aim is simple: get the finance organised so you can focus on building the home." },
    ],
  },
  "asset-finance-cash-versus-finance-business": {
    title: "Buying equipment or a vehicle? Here’s how finance can keep more cash working in the business",
    summary: "Paying cash is one option. Financing the asset can preserve working capital for wages, stock, growth and the next opportunity. The right structure depends on what the business needs the cash to do.",
    sections: [
      { heading: "Make the asset earn before you drain the cash", body: "If a vehicle, machine or piece of equipment is going to generate revenue or save time, it can make sense to let the asset help pay for itself over time. That keeps more cash available for the parts of the business that do not come with finance attached—wages, stock, marketing, tax and opportunities. We compare cash and finance side by side so you can see what the business looks like after the purchase, not just what the interest rate is." },
      { heading: "Match the repayments to the asset", body: "The finance term should reflect how long the asset will be useful and how it produces value. A longer term can reduce the monthly payment. A shorter term clears the debt sooner. A balloon can preserve cash flow. We model the options around the business rather than choosing whatever structure makes the first repayment look smallest." },
      { heading: "Use the lender that understands the asset", body: "Mainstream vehicles are easy. Specialised machinery, older equipment and private sales can need a more tailored lender. That is where access to a broader panel matters. We look for lenders that are comfortable with the asset and the business, which can create better options than accepting the first dealer finance quote on the table." },
      { heading: "Keep the documentation practical", body: "Depending on the business and lender, there may be streamlined or alternative documentation options available. We work out what evidence is actually needed before the application starts. If full financials are strong, we use them. If another evidence pathway fits better, we compare that. The goal is to get the asset funded efficiently without turning the purchase into a six-week paperwork exercise." },
      { heading: "Bring the accountant into the structure, not the sales pitch", body: "Tax treatment should be confirmed with your accountant. We focus on the finance structure and cash flow, then make sure it can sit alongside the accounting advice. That gives you a clearer decision than trying to choose a product because someone said it was ‘better for tax’." },
      { heading: "Your next move", body: "Before you pay cash or sign dealer finance, send us the asset price and what you want the repayments to look like. We can compare deposit, term, balloon and lender options and show you how much cash stays in the business under each structure. The asset should help the business grow without quietly emptying the bank account." },
    ],
  },
  "moving-melbourne-to-regional-victoria-finance": {
    title: "Moving from Melbourne to regional Victoria? Here’s how to finance the lifestyle change",
    summary: "A regional move can unlock more space, acreage, a different pace and often a very different property budget. The finance works best when the sale, purchase, income and property type are planned together.",
    sections: [
      { heading: "Start with the life you are moving toward", body: "A regional move is rarely just about buying a cheaper house. It might be more land, more space for the family, working differently, starting a business or getting out of the metro grind. That matters because the finance should be built around the change you are actually making. We map the current home, likely sale proceeds, new purchase range and income position so you can see what the move can unlock." },
      { heading: "Use the equity difference strategically", body: "Selling a Melbourne property and buying regionally can create a meaningful equity release. That gives you choices. You might reduce debt heavily, keep a large offset buffer, renovate, buy acreage or preserve some capital for investment or business. We model the options before settlement so the equity has a purpose rather than simply disappearing into the new purchase because it is there." },
      { heading: "Make the employment transition part of the finance plan", body: "If you are keeping the same job, moving to hybrid work, changing employers or starting something new, we check how the lender will view the income before you commit. Often there is a clean pathway. The earlier we know the employment plan, the easier it is to select the right lender and timing." },
      { heading: "Finance the regional property you actually want", body: "The next home might have more land, a shed, tank water, septic or another dwelling. That is normal in regional Victoria. We review the property characteristics and choose lenders that are comfortable with them. You do not need to turn the dream property into a suburban box just to get finance. You need the lender and property to match." },
      { heading: "Choose the sale and purchase sequence", body: "You may sell first, buy first, bridge or line the settlements up. We compare those pathways using the real numbers. That lets you decide how much certainty and flexibility you want while moving between two different property markets. The right structure can give you more time to buy well rather than rushing because the old house settled first." },
      { heading: "Your next move", body: "If regional Victoria is the next chapter, start the finance conversation before you list or offer. We can model the city sale, regional purchase, equity position, income changes and any acreage issues so you know what the move can look like before you make it." },
    ],
  },
  "professional-upgrader-safe-purchase-range": {
    title: "Ready for the bigger home? Here’s how to upgrade without putting the rest of the plan on hold",
    summary: "A strong income gives you options. The goal is to use that capacity to get the home you want while keeping room for investing, family changes, business plans and the next move after this one.",
    sections: [
      { heading: "Use your income to create options, not just a bigger maximum", body: "Higher-income households can often borrow a lot. That is useful because it gives you choice. We take the lender maximum and turn it into a practical range based on the repayment you are comfortable carrying and the other things you still want to fund. That means the new home can be a step forward without every other goal being parked indefinitely." },
      { heading: "Decide whether the current home has another job", body: "If there is strong equity in the existing home, keeping it as an investment may be possible. Selling it may also put you in a much stronger new-home position. We model both pathways before you decide. That shows you the change in debt, cash flow, equity and future borrowing capacity. Then you can take the numbers to your accountant or adviser where tax and investment advice is needed and make the decision with the full picture." },
      { heading: "Use bridging when timing is the problem", body: "If the right home appears before you are ready to sell, buy-first and bridging options may allow you to move without rushing the sale. We model the peak debt and end debt and compare that with selling first. The goal is to give you options around timing, not force you into one sequence because the finance was left too late." },
      { heading: "Build the loan around how your household actually earns", body: "Bonuses, commissions, irregular lump sums and business distributions can make offset and repayment flexibility valuable. We look at how cash actually moves through the household and then choose features that suit that pattern. Sometimes the basic loan is right. Sometimes a strong offset structure creates more value. The product should fit the way you live, not the other way around." },
      { heading: "Keep the next investment or business move alive", body: "If investing or business growth is part of the five-year picture, we can model how the upgrade affects future capacity before you buy. That may influence the purchase price, lender or equity contribution. A small decision now can preserve a meaningful option later. This is exactly why we think beyond the single approval." },
      { heading: "Your next move", body: "Before you start stretching the property filters higher, let’s set the range properly. We can model the new home, keep-versus-sell, bridging if needed and the effect on future borrowing capacity. Then you can go shopping with a much clearer idea of where the sweet spot sits." },
    ],
  },
};

export function applyArticleVoice(article: ArticleData): ArticleData {
  const override = bySlug[article.slug];
  return override ? { ...article, ...override } : article;
}

export function applyArticleVoiceToMany(articles: ArticleData[]): ArticleData[] {
  return articles.map(applyArticleVoice);
}
