import { assets } from "@/lib/siteData";

export type SolutionRecord = {
  slug: string;
  hub: "purchase" | "refinance" | "investment" | "business" | "agri-rural" | "asset";
  eyebrow: string;
  title: string;
  intro: string;
  challenge: string;
  image: string;
  decisions: Array<{ title: string; body: string }>;
  sequence: Array<{ title: string; body: string }>;
  questions: string[];
  loanTypes: Array<{ label: string; href: string }>;
  faq: Array<{ question: string; answer: string }>;
};

const records: SolutionRecord[] = [
  {
    slug: "purchase", hub: "purchase", eyebrow: "PURCHASE SOLUTIONS", title: "Buy the property. Keep the plan intact.",
    intro: "The purchase price is only one decision. Deposit, buffers, sale timing, property type, lender policy and the goals after settlement all shape the right path.",
    challenge: "What does this purchase need to leave possible?", image: assets.homeProperty,
    decisions: [
      { title: "What are you buying?", body: "A first home, upgrade, build, acreage property or renovation can each change policy, valuation and evidence." },
      { title: "What happens to the current property?", body: "Selling, keeping or bridging changes peak debt, cash flow, equity and timing risk." },
      { title: "How much buffer remains?", body: "A workable approval should still leave room for costs, surprises and the next move." },
    ],
    sequence: [
      { title: "Define the outcome", body: "Clarify the property, timing, household priorities and what cannot be compromised." },
      { title: "Model realistic paths", body: "Compare deposits, sale assumptions, construction stages, bridging exposure and lender fit." },
      { title: "Choose the sequence", body: "Set the order of pre-approval, sale, contract, valuation and settlement before pressure rises." },
    ],
    questions: ["Can we buy before we sell?", "Will the lender accept this property?", "Should we use more deposit or keep a larger buffer?", "How will this affect the next investment or business move?"],
    loanTypes: [{ label: "Home loans", href: "/services/home-loans" }, { label: "Bridging finance", href: "/services/bridging-finance" }, { label: "Construction loans", href: "/services/construction-loans" }, { label: "Acreage & rural finance", href: "/services/acreage-rural-finance" }],
    faq: [{ question: "Should I get pre-approved before looking?", answer: "A useful pre-approval can clarify a lender position and likely conditions, but it is not a guarantee. Property acceptability, valuation, evidence and changes in circumstances can still matter." }, { question: "Is the maximum approval the right budget?", answer: "Not automatically. A lending limit does not know your savings goals, preferred buffer, future plans or tolerance for repayments. The budget should be a household decision, not just a bank output." }],
  },
  {
    slug: "refinance", hub: "refinance", eyebrow: "REFINANCE SOLUTIONS", title: "Change the structure—not just the rate.",
    intro: "A lower rate can help, but the strongest refinance starts with what the new structure should improve: cash flow, clarity, flexibility, debt separation or access to equity.",
    challenge: "What should be different after the refinance?", image: assets.homeProperty,
    decisions: [
      { title: "Cost versus benefit", body: "Compare switching costs, break costs where relevant, loan features and the time needed to recover the change." },
      { title: "Term and total interest", body: "Resetting a loan to a longer term can reduce repayments while increasing the time and interest paid." },
      { title: "Purpose and separation", body: "Keep private, investment and business debt purposes clear when consolidating or releasing equity." },
    ],
    sequence: [{ title: "Audit the current position", body: "Review balances, rates, limits, offsets, fixed terms, purposes and security." }, { title: "Name the improvement", body: "Set the cash-flow, structure or flexibility outcome before comparing products." }, { title: "Test the full cost", body: "Model fees, term changes, repayment behaviour and the risks of moving unsecured debt into a home loan." }],
    questions: ["Will a lower repayment extend the debt?", "Should debts be combined or kept separate?", "Can equity be released responsibly?", "Does the lender still fit the next move?"],
    loanTypes: [{ label: "Refinancing", href: "/services/refinancing" }, { label: "Debt consolidation", href: "/services/debt-consolidation" }, { label: "Investment loans", href: "/services/investment-property-loans" }],
    faq: [{ question: "Should I refinance for a small rate difference?", answer: "The rate difference is only one input. Fees, remaining term, features, lender policy and how long you expect to keep the loan can change the value of switching." }, { question: "Can refinancing create equity?", answer: "Refinancing does not create equity, but it may provide access to available equity if the valuation, serviceability, purpose and lender policy support it." }],
  },
  {
    slug: "investment", hub: "investment", eyebrow: "INVESTMENT SOLUTIONS", title: "The next property depends on the structure before it.",
    intro: "Investment lending is not a single borrowing-capacity number. Equity, rental treatment, lender order, security and the existing portfolio can all influence what remains possible.",
    challenge: "Is the constraint your plan—or one lender’s policy?", image: assets.hero,
    decisions: [{ title: "Capacity", body: "Understand how different lenders assess income, rent, existing debt and expenses before treating one result as universal." }, { title: "Equity", body: "Choose how much equity to use, what buffer to retain and how to keep purposes traceable." }, { title: "Lender sequence", body: "The lender used today can affect flexibility, pricing and capacity for the property after this one." }],
    sequence: [{ title: "Map the portfolio", body: "List ownership, values, balances, limits, rates, securities, rents and loan purposes." }, { title: "Model the next two moves", body: "Test the immediate purchase and the capacity or risk position it leaves behind." }, { title: "Coordinate advice", body: "Keep lending decisions connected to independent tax, legal and financial advice where relevant." }],
    questions: ["Should I use cash or equity for the deposit?", "Will cross-collateralisation reduce flexibility?", "Which lender order protects future capacity?", "What buffer still works if rates, rent or expenses change?"],
    loanTypes: [{ label: "Investment property loans", href: "/services/investment-property-loans" }, { label: "Portfolio lending", href: "/services/portfolio-lending" }, { label: "SMSF property loans", href: "/services/smsf-property-loans" }],
    faq: [{ question: "Have I reached my borrowing limit?", answer: "Possibly, but a result can also reflect one lender’s policy and the current portfolio structure. A review should test the wider position without assuming more debt is automatically appropriate." }, { question: "Should all investment loans be with one lender?", answer: "Not necessarily. Simplicity, pricing, security control, policy and future capacity all matter. The right arrangement depends on the portfolio and next move." }],
  },
  {
    slug: "business", hub: "business", eyebrow: "BUSINESS SOLUTIONS", title: "Finance the opportunity. Keep cash flow visible.",
    intro: "Business finance should connect the purpose of the funds, the evidence, the repayment source and the value the move is expected to create.",
    challenge: "What should the funding help the business produce?", image: assets.businessCommercial,
    decisions: [{ title: "Purpose", body: "Growth capital, working capital, premises, acquisition and equipment each call for a different structure and term." }, { title: "Evidence", body: "Accounts, tax returns, management figures, forecasts and contracts tell different parts of the operating story." }, { title: "Cash-flow fit", body: "Repayment timing should recognise seasonality, useful life, implementation time and the buffer the business still needs." }],
    sequence: [{ title: "Translate the opportunity", body: "Define the amount, use, timing and commercial outcome in practical terms." }, { title: "Build the evidence story", body: "Connect historic performance, current trading and relevant forward evidence without hiding complexity." }, { title: "Match term to value", body: "Choose a facility, term and repayment profile that reflect how and when the funding creates value." }],
    questions: ["Why does taxable income differ from the business story?", "Should the business use cash or finance?", "What security and guarantees may be required?", "How much working capital remains after the move?"],
    loanTypes: [{ label: "Business finance", href: "/services/business-finance" }, { label: "Commercial property finance", href: "/services/commercial-property-finance" }, { label: "Working capital", href: "/services/working-capital" }, { label: "Equipment finance", href: "/services/equipment-finance" }],
    faq: [{ question: "Why can a profitable business still struggle to borrow?", answer: "Taxable income, accounting treatment, business structure, retained profit, one-off costs and lender evidence rules can make a strong operation appear different in a standard assessment." }, { question: "Should the term match the asset?", answer: "Usually the useful life and expected value creation are important inputs. Financing an asset long after its productive value has faded can pressure future cash flow." }],
  },
  {
    slug: "agri-rural", hub: "agri-rural", eyebrow: "AGRI & RURAL SOLUTIONS", title: "The property and operation must make sense to the lender.",
    intro: "Land size, zoning, access, services, improvements, location and intended use can change the way a lender assesses a regional or rural opportunity.",
    challenge: "Will the lender see the property the way you do?", image: assets.regionalAcreage,
    decisions: [{ title: "Property acceptability", body: "Share the address, listing, land details, access, improvements and intended use early enough to investigate." }, { title: "Income and operation", body: "Employment, contracting, farming and business income may require different evidence and interpretation." }, { title: "Future work", body: "Renovation, sheds, machinery, subdivision assumptions and construction can change the funds and buffer required." }],
    sequence: [{ title: "Investigate before emotion", body: "Check security and valuation questions before contract pressure narrows lender choice." }, { title: "Connect property and borrower", body: "Present the purpose, income, operations and property in one coherent lending story." }, { title: "Plan the whole move", body: "Include purchase costs, works, equipment, seasonal needs and a realistic contingency." }],
    questions: ["Is the acreage standard residential security?", "Will zoning or commercial use change policy?", "How will sheds and other improvements be valued?", "Should machinery be financed separately from the property?"],
    loanTypes: [{ label: "Acreage & rural finance", href: "/services/acreage-rural-finance" }, { label: "Construction loans", href: "/services/construction-loans" }, { label: "Machinery finance", href: "/services/machinery-finance" }, { label: "Commercial property finance", href: "/services/commercial-property-finance" }],
    faq: [{ question: "Is acreage always harder to finance?", answer: "No. The answer depends on land size, location, access, services, zoning, improvements, use and lender policy. Early property detail makes the assessment more useful." }, { question: "Can a rural property be treated as a normal home?", answer: "Sometimes. A residential appearance or address does not by itself determine lender treatment. The security and intended use still need to fit policy." }],
  },
  {
    slug: "asset", hub: "asset", eyebrow: "ASSET SOLUTIONS", title: "Put the asset to work without draining the business.",
    intro: "Cash avoids finance cost. Finance preserves cash. The right answer depends on what the asset and the retained capital can each produce.",
    challenge: "What value should this asset create—and over what useful life?", image: assets.businessCommercial,
    decisions: [{ title: "Cash versus finance", body: "Compare interest and fees with the value of keeping liquidity for wages, stock, marketing or another opportunity." }, { title: "Useful life", body: "Match the term and residual assumptions to how long the asset is expected to remain productive." }, { title: "Ownership and advice", body: "Coordinate the lending structure with qualified accounting and tax advice before relying on treatment assumptions." }],
    sequence: [{ title: "Define the job", body: "Identify the vehicle, equipment or machinery, supplier, timing and expected use." }, { title: "Protect operating cash", body: "Model deposit, repayments, seasonal cash flow and the liquidity left after purchase." }, { title: "Compare structures", body: "Review facility type, term, security, documentation and flexibility before ordering the asset." }],
    questions: ["Should the business pay cash or preserve liquidity?", "How quickly will the asset create revenue or capacity?", "Does the term fit its useful life?", "What documentation can support the purchase?"],
    loanTypes: [{ label: "Asset finance", href: "/services/asset-finance" }, { label: "Vehicle finance", href: "/services/vehicle-finance" }, { label: "Equipment finance", href: "/services/equipment-finance" }, { label: "Machinery finance", href: "/services/machinery-finance" }],
    faq: [{ question: "Is paying cash always cheaper?", answer: "It avoids finance cost, but it also uses liquidity. The relevant comparison includes what retained cash could support and the buffer the business needs." }, { question: "How quickly can asset finance be arranged?", answer: "Timing depends on the asset, borrower, amount, supplier, evidence and lender. Starting with complete details usually makes the pathway clearer." }],
  },
];

const detail = (record: Omit<SolutionRecord, "image"> & { image?: string }): SolutionRecord => ({ ...record, image: record.image ?? assets.homeProperty });

records.push(
  detail({ slug: "first-home", hub: "purchase", eyebrow: "FIRST HOME SOLUTION", title: "Buy the first home without making the first loan the whole plan.", intro: "Deposit, grants or schemes, lender policy, property choice and buffer all interact. The goal is not only to reach settlement; it is to begin from a workable position.", challenge: "What will make the first home sustainable after the keys?", decisions: [{ title: "Deposit and costs", body: "Separate the deposit from stamp duty, legal, inspection, moving and immediate property costs." }, { title: "Scheme and guarantor fit", body: "Eligibility, guarantees and lender participation need to be confirmed for the actual scenario." }, { title: "Property acceptability", body: "Apartments, new builds, titled land and unusual properties can carry different lender rules." }], sequence: [{ title: "Set the household budget", body: "Choose a repayment and buffer that fit real life rather than starting with the maximum loan." }, { title: "Verify the pathway", body: "Check deposit sources, scheme rules, evidence and likely property constraints." }, { title: "Prepare before the contract", body: "Understand approval conditions and who needs to act once a property is found." }], questions: ["How much deposit do we really need?", "Could a guarantee or scheme help?", "What costs sit outside the purchase price?", "What could change after pre-approval?"], loanTypes: [{ label: "First-home buyer loans", href: "/services/first-home-buyers" }, { label: "Guarantor loans", href: "/services/guarantor-loans" }, { label: "Home loans", href: "/services/home-loans" }], faq: [{ question: "Does pre-approval guarantee finance?", answer: "No. It is generally conditional and can still depend on the property, valuation, evidence, lender policy and unchanged circumstances." }, { question: "Should I use every dollar for the deposit?", answer: "Keeping a realistic buffer for costs and surprises can be more important than maximising the deposit. The right balance depends on the full position." }] }),
  detail({ slug: "first-investment-property", hub: "investment", eyebrow: "FIRST INVESTMENT SOLUTION", title: "The first investment should leave room for the second decision.", intro: "The deposit is only the beginning. Ownership, equity, loan purpose, lender selection, buffers and future serviceability can shape the portfolio long after settlement.", challenge: "How do you buy the first property without shrinking the next opportunity?", decisions: [{ title: "Cash or equity", body: "Compare traceability, buffer, security control and the effect on existing home debt." }, { title: "Interest and repayment structure", body: "Cash flow, total cost and tax treatment require separate lending and professional-advice conversations." }, { title: "Lender order", body: "The first investment lender can influence policy flexibility for the next property." }], sequence: [{ title: "Define the investment plan", body: "Clarify the purpose, timeframe, buffer and likely next move." }, { title: "Map the funding", body: "Separate deposit, costs, equity and borrowing so purposes remain understandable." }, { title: "Stress the position", body: "Test rate, vacancy, expense and income changes before choosing the maximum." }], questions: ["Should we use home equity?", "How much buffer should remain?", "Which lender protects future capacity?", "What advice is needed before choosing ownership?"], loanTypes: [{ label: "Investment property loans", href: "/services/investment-property-loans" }, { label: "Portfolio lending", href: "/services/portfolio-lending" }], faq: [{ question: "Can a broker advise on ownership structure or tax?", answer: "A broker can explain lending implications, but ownership, tax and legal decisions should be made with appropriately qualified advisers." }, { question: "Is interest-only always better for investors?", answer: "No. Cash flow, total interest, principal reduction, lender policy and the wider strategy all need to be considered." }] }),
  detail({ slug: "renovating-a-home", hub: "purchase", eyebrow: "RENOVATION SOLUTION", title: "Fund the renovation without underestimating the build around it.", intro: "A renovation can be funded from savings, available equity, a loan increase or construction-style progress payments. The right path depends on scope, contracts, valuation and buffer.", challenge: "Is the finance matched to the work—or only the first quote?", decisions: [{ title: "Scope and evidence", body: "Cosmetic work, structural renovation and extensions can require different contracts, approvals and lender processes." }, { title: "Upfront versus staged funding", body: "The way funds are released affects builder payments, inspections and cash-flow timing." }, { title: "Contingency", body: "Older properties and changed scope make a realistic buffer essential." }], sequence: [{ title: "Define the real scope", body: "Bring plans, approvals, quotes and the likely contingency into one budget." }, { title: "Check equity and valuation", body: "Understand current and, where relevant, proposed value assumptions before committing." }, { title: "Match drawdowns to works", body: "Coordinate lender conditions and payment timing with the builder and contract." }], questions: ["Will the lender use current or completed value?", "Is a standard top-up enough?", "When will the builder need funds?", "What happens if the scope changes?"], loanTypes: [{ label: "Renovation finance", href: "/services/renovation-finance" }, { label: "Construction loans", href: "/services/construction-loans" }, { label: "Refinancing", href: "/services/refinancing" }], faq: [{ question: "Can equity fund a renovation?", answer: "It may, if valuation, serviceability, loan purpose and lender policy support the increase. Available equity is not automatically an approved amount." }, { question: "Do renovations always need a construction loan?", answer: "No. Scope, contract, structural work, amount and lender rules determine whether staged construction funding is needed." }] }),
  detail({ slug: "refinance-debt-consolidation", hub: "refinance", eyebrow: "DEBT CONSOLIDATION SOLUTION", title: "A smaller repayment can still become a larger long-term cost.", intro: "Consolidation can simplify cash flow, but moving short-term debt into a long home-loan term can increase total interest and place the home behind debt that was previously unsecured.", challenge: "Will the structure solve the pressure—or only spread it out?", decisions: [{ title: "Repayment relief", body: "Compare the immediate monthly change with the term and total interest under realistic repayment behaviour." }, { title: "Security risk", body: "Understand which debts become secured against property and what that means." }, { title: "Cause and control", body: "A new structure needs a plan for limits, spending, buffers and the reason the debt accumulated." }], sequence: [{ title: "List every debt", body: "Capture balances, limits, rates, repayments, terms, fees and security." }, { title: "Model both horizons", body: "Compare short-term cash flow and the long-term cost at minimum and planned repayments." }, { title: "Close the loop", body: "Set repayment and account actions so cleared facilities do not quietly rebuild." }], questions: ["How much interest will be paid over the new term?", "Will unsecured debt become secured?", "Which accounts should close?", "What repayment gets the debt cleared sooner?"], loanTypes: [{ label: "Debt consolidation", href: "/services/debt-consolidation" }, { label: "Refinancing", href: "/services/refinancing" }], faq: [{ question: "Does consolidation reduce the debt?", answer: "No. It changes the structure and potentially the rate or repayment. The balance only reduces through repayment or other funds." }, { question: "Can consolidation harm future borrowing capacity?", answer: "The new balance, limits, term, repayment and behaviour can all affect future assessments. The goal should include a credible reduction plan." }] }),
  detail({ slug: "buying-your-next-home", hub: "purchase", eyebrow: "NEXT HOME SOLUTION", title: "More home. Keep the future options.", intro: "The next home can involve selling, keeping, bridging, renovating or building. The best sequence balances certainty, peak debt, timing and the life you want after settlement.", challenge: "Should you sell first, buy first, keep—or build?", decisions: [{ title: "Sell or retain", body: "Compare debt, equity, cash flow, tax advice and the future role of the existing property." }, { title: "Timing", body: "Selling first creates price certainty; buying first can protect property choice while increasing peak exposure." }, { title: "Future capacity", body: "The upgrade should not make every investment, family or business decision harder." }], sequence: [{ title: "Model four paths", body: "Compare sell-first, buy-first, retain and build scenarios before choosing by habit." }, { title: "Set acceptable pressure", body: "Define peak debt, repayment, time and contingency limits." }, { title: "Coordinate the move", body: "Align agents, contracts, lender conditions, valuation, conveyancing and settlement dates." }], questions: ["Can we afford to buy before selling?", "Should the current home become an investment?", "What if the sale takes longer?", "What buffer remains after moving costs and works?"], loanTypes: [{ label: "Upgrading", href: "/services/upgrading" }, { label: "Bridging finance", href: "/services/bridging-finance" }, { label: "Home loans", href: "/services/home-loans" }], faq: [{ question: "Is bridging finance always the buy-first answer?", answer: "No. Timing, saleability, peak debt, income, valuation, lender policy and alternatives all matter." }, { question: "Should we keep the existing home?", answer: "That depends on cash flow, debt, equity, investment fit and independent tax or financial advice—not only emotional attachment or a rough rental estimate." }] }),
  detail({ slug: "fund-business-growth", hub: "business", eyebrow: "BUSINESS GROWTH SOLUTION", title: "Fund growth without making the cash-flow gap invisible.", intro: "Growth can consume cash before it produces it. The funding structure should recognise implementation time, working-capital needs, evidence and the commercial result the move is expected to create.", challenge: "When will the investment begin paying the business back?", decisions: [{ title: "Use of funds", body: "Separate stock, people, marketing, fit-out, acquisition, equipment and contingency needs." }, { title: "Time to value", body: "Repayments may begin before the growth move reaches full productivity." }, { title: "Evidence", body: "Historic accounts, current performance, contracts and realistic forecasts support different parts of the case." }], sequence: [{ title: "Build the funding map", body: "Show amount, timing, use and the cash the business needs to keep operating." }, { title: "Explain the operating story", body: "Connect past results, current trading and the reason the growth opportunity exists." }, { title: "Choose the facility", body: "Match term, access and repayment to the duration and uncertainty of the need." }], questions: ["Is this term funding or working capital?", "How long before revenue catches up?", "What evidence supports the plan?", "What happens if implementation takes longer?"], loanTypes: [{ label: "Business finance", href: "/services/business-finance" }, { label: "Working capital", href: "/services/working-capital" }, { label: "Line of credit", href: "/services/line-of-credit" }], faq: [{ question: "Are forecasts enough to secure finance?", answer: "Usually not on their own. Lenders may consider historic, current and forward evidence differently, depending on the purpose and risk." }, { question: "Should working capital use a long-term loan?", answer: "The duration and recurring nature of the need matter. A permanent funding gap and a short timing gap may require different solutions." }] }),
  detail({ slug: "business-premises", hub: "business", eyebrow: "BUSINESS PREMISES SOLUTION", title: "Buy the premises without starving the business inside it.", intro: "Commercial property brings the business, property, entity structure, deposit, valuation, lease position and working-capital needs into one decision.", challenge: "Will owning the property strengthen the operation—or constrain it?", decisions: [{ title: "Deposit and costs", body: "Commercial deposits, valuation, legal work and transaction costs can differ materially from a home purchase." }, { title: "Borrower and owner", body: "Entity, lease and ownership decisions need legal, tax and accounting advice alongside finance." }, { title: "Operational buffer", body: "Protect the cash needed for fit-out, stock, wages and the move itself." }], sequence: [{ title: "Separate property and business needs", body: "Budget the property, costs, fit-out, relocation and working capital distinctly." }, { title: "Present both stories", body: "Explain the property security and the business repayment source." }, { title: "Coordinate specialists", body: "Bring lender, accountant, lawyer, conveyancer and valuer questions together early." }], questions: ["Who should own the property?", "How will the business occupy it?", "What deposit and valuation basis apply?", "How much cash must remain after settlement?"], loanTypes: [{ label: "Commercial property finance", href: "/services/commercial-property-finance" }, { label: "Business finance", href: "/services/business-finance" }], faq: [{ question: "Is commercial-property lending the same as a home loan?", answer: "No. Deposit, term, pricing, valuation, evidence, review conditions and repayment structures can differ." }, { question: "Can a broker choose the ownership entity?", answer: "No. A broker can explain lending implications, but legal, tax and ownership advice should come from appropriately qualified advisers." }] }),
  detail({ slug: "release-equity", hub: "refinance", eyebrow: "EQUITY RELEASE SOLUTION", title: "Equity is an option—not free cash.", intro: "Available equity can support renovation, investment, business or another goal, but the loan still increases, the purpose matters and the repayment must fit.", challenge: "What will the released funds create—and what debt will remain?", decisions: [{ title: "Available versus usable equity", body: "Valuation, lender limits and serviceability determine what may be approved." }, { title: "Purpose", body: "Keep loan splits and records aligned to how funds are actually used." }, { title: "Repayment", body: "Model the higher debt, rate changes and future income rather than relying on current equity alone." }], sequence: [{ title: "Value and map", body: "Estimate property value, balances, limits and genuine equity after lender constraints." }, { title: "Define the purpose", body: "Set amount, timing, use and how long funds may remain undrawn." }, { title: "Structure for clarity", body: "Separate purposes and coordinate tax or legal advice where relevant." }], questions: ["How much equity is actually usable?", "Should funds be released now or later?", "How should purposes be separated?", "What repayment and buffer remain?"], loanTypes: [{ label: "Refinancing", href: "/services/refinancing" }, { label: "Investment property loans", href: "/services/investment-property-loans" }, { label: "Renovation finance", href: "/services/renovation-finance" }], faq: [{ question: "Does having equity guarantee approval?", answer: "No. Valuation, serviceability, purpose, credit position and lender policy still apply." }, { question: "Can released equity be used for an investment deposit?", answer: "It may be possible, but purpose tracing, structure and professional tax advice are important before funds are mixed or used." }] }),
  detail({ slug: "bridging-finance", hub: "purchase", eyebrow: "BRIDGING SOLUTION", title: "Buy before you sell—with the exit path visible.", intro: "Bridging can create time and property choice, but it also creates peak debt, sale-price, timing, valuation and interest assumptions that need to be understood before commitment.", challenge: "What happens if the current property sells later—or for less?", decisions: [{ title: "Peak debt", body: "Understand the highest combined exposure, repayment approach and interest treatment." }, { title: "Exit value", body: "Use realistic sale proceeds after selling costs and any lender requirements." }, { title: "Time", body: "Know the expected sale period, maximum bridge period and contingency if the market takes longer." }], sequence: [{ title: "Model the sale", body: "Use evidence-based price ranges, costs and timeframes rather than the best-case result." }, { title: "Calculate the bridge", body: "Map existing debt, new purchase, funds, peak exposure and residual loan." }, { title: "Set the exit actions", body: "Coordinate listing, contract, valuation, settlement and lender conditions." }], questions: ["What is the peak debt?", "How is interest paid or capitalised?", "What sale value is assumed?", "What is the fallback if timing changes?"], loanTypes: [{ label: "Bridging finance", href: "/services/bridging-finance" }, { label: "Upgrading", href: "/services/upgrading" }, { label: "Home loans", href: "/services/home-loans" }], faq: [{ question: "Do I have to make repayments on both properties?", answer: "Structures differ. Some may require payments; some may capitalise interest subject to policy. The total cost and peak exposure still need to be understood." }, { question: "What if the property does not sell in time?", answer: "The available options depend on the loan terms, lender and circumstances. A credible sale and contingency plan should exist before entering the bridge." }] }),
  detail({ slug: "building-your-home", hub: "purchase", eyebrow: "CONSTRUCTION SOLUTION", title: "Build the home. Plan the cash flow between the stages.", intro: "Construction finance is a sequence of land, contract, valuation, approvals, deposits, progress payments, variations and final completion—not one settlement event.", challenge: "Who needs funds, evidence or approval at every stage?", decisions: [{ title: "Total project cost", body: "Include land, build, upgrades, site costs, professional fees, rent or holding costs and contingency." }, { title: "Valuation and contribution", body: "The lender may assess contract, land and completed value differently from the budget." }, { title: "Progress payments", body: "Builder invoices, inspections and lender drawdowns need to align so work is not delayed." }], sequence: [{ title: "Build the full budget", body: "Reconcile contract, inclusions, exclusions, site work, variations and contingency." }, { title: "Clear the conditions", body: "Prepare plans, permits, builder evidence, valuation and borrower contributions." }, { title: "Manage every draw", body: "Track invoices, inspections, interest and remaining contingency through completion." }], questions: ["What is excluded from the contract?", "How are site costs and variations funded?", "When are repayments or interest due?", "What must be complete before each draw?"], loanTypes: [{ label: "Construction loans", href: "/services/construction-loans" }, { label: "Home loans", href: "/services/home-loans" }, { label: "Acreage & rural finance", href: "/services/acreage-rural-finance" }], faq: [{ question: "Does the lender pay the builder upfront?", answer: "Usually construction funds are released in stages after required documents and inspections, according to the contract and lender process." }, { question: "What happens if the build costs more?", answer: "Variations and overruns may not automatically be funded. A contingency and early communication are important, and additional approval may be required." }] }),
);

export const solutions = records;
export const getSolution = (slug?: string) => solutions.find(record => record.slug === slug);

