import { Link, useParams } from "wouter";
import { ArrowLeft, ArrowRight, Clock, RefreshCw } from "lucide-react";
import { Seo, breadcrumbSchema, organizationSchema } from "@/components/Seo";
import { Eyebrow } from "@/components/Shared";
import { SiteLayout } from "@/components/SiteChrome";
import NotFound from "@/pages/NotFound";
import { articles as launchArticles } from "@/lib/articleLibrary";
import { founder, siteUrl } from "@/lib/siteData";
import { getWebsiteService } from "@/lib/serviceCatalog";
import { mergeCmsArticles } from "@/lib/cmsContent";
import { usePublicData, type CmsArticleRow } from "@/lib/publicApi";

const displayDate = (value?: string) => value ? new Date(value).toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" }) : "18 August 2026";
const words = (value:string) => value.trim().split(/\s+/).filter(Boolean).length;

const depthGuidance: Record<string,string> = {
  Investment: "Before acting, bring the whole position together: current home value and debt, cash savings, available equity, income, existing credit limits, proposed purchase range and the next property you might want after this one. Then stress-test the position. What happens if rates move, rent is lower than expected, the property is vacant for a period or your income changes? The point is not to predict every event. It is to make sure the investment is not dependent on a perfect run. Lender policy also changes over time, so borrowing capacity should be recalculated before each purchase rather than assumed from the previous approval. If tax outcomes, ownership structures or deductibility are part of the decision, get advice from your accountant before moving money or setting up loan splits. Finance should support the investment strategy, not accidentally become the strategy.",
  Upgrading: "Before you commit, write down the current home value, mortgage, expected selling costs, available cash, comfortable monthly repayment and the amount you want left in reserve after the move. Then compare sell-first, buy-first and any bridging pathway using conservative assumptions. If you are considering keeping the current home, model that separately because the debt, rent, tax position and future borrowing capacity can change materially. The goal is to know the safe range before the property search becomes emotional. A bigger home can be a great move. It should not require every other goal to be put on hold simply because a lender was prepared to approve the maximum.",
  Business: "For business owners, the quality of the evidence matters as much as the headline profit. Keep current financial statements, tax returns, BAS, ATO account information and entity documents organised, and be ready to explain material changes between years. Separate one-off costs from recurring costs, but do not assume every expense can be added back under lender policy. If money is moving from the business into a personal property strategy, involve the accountant early so tax, working capital and ownership decisions are not made purely to satisfy a loan application. The strongest outcome is usually the one where the business remains well funded and the personal balance sheet improves at the same time.",
  "First Home": "Before making an offer, know four numbers: your maximum lender approval, your own comfortable purchase range, the cash required at settlement and the buffer you want left afterwards. Check concessions and government scheme eligibility using current official settings rather than assumptions from a friend or an old article. Review credit-card limits, personal loans and HELP obligations because they can affect servicing. Finally, remember that pre-approval is conditional. The property still needs to fit lender policy and valuation requirements. The job of the plan is to make the first purchase feel controlled rather than rushed.",
  "Regional & Rural": "For a regional or acreage property, send the listing or address before relying on a generic borrowing figure. Land size, zoning, access, services, sheds, multiple dwellings, business use and comparable sales can change lender appetite or valuation. Keep a buffer for valuation risk and avoid assuming every improvement adds dollar-for-dollar value. If employment is also changing because of a regional move, resolve how the lender will evidence the new income before the contract becomes unconditional. Local property knowledge helps identify the right questions earlier, but lender policy still decides what is acceptable security.",
  Refinancing: "A useful refinance review should compare the current and proposed loan on the same time horizon. Include switching costs, monthly fees, the remaining term, the proposed term, repayment changes and interest over a defined period. If the new loan extends the term, model what happens if repayments are kept at the old level as well. If equity is being released, separate that borrowing into a clearly defined purpose and obtain tax advice where relevant. The result should show a real improvement in cost, cash flow, flexibility or strategic capacity. If it does not, staying with the existing lender can be the better move.",
  Construction: "Before the build starts, keep one funding schedule that shows land cost, building contract, known variations, site costs, cash contribution, approved loan, contingency and estimated out-of-pocket items outside the contract. Understand when the lender expects your cash contribution to be used and how progress payments will be requested. Do not assume variations can simply be added to the construction loan later. If the valuation comes in below total project cost, know where the difference will come from. Construction works best when finance is treated as part of the project plan from day one.",
  Assets: "Before choosing cash, dealer finance or a separate asset lender, compare deposit, repayment, term, balloon or residual, total finance cost and the cash left in the business after purchase. Then ask what that retained cash needs to fund over the same period. Match the finance term to the asset’s useful life and get accounting or tax advice on the structure rather than relying on a sales pitch. For used or specialised assets, check lender appetite before paying a non-refundable deposit. The finance should help the asset create productive capacity without quietly creating a working-capital problem.",
};

const relationshipScore = (current: ReturnType<typeof mergeCmsArticles>[number], candidate: ReturnType<typeof mergeCmsArticles>[number]) => {
  const sharedTags = (current.tags ?? []).filter(tag => (candidate.tags ?? []).includes(tag)).length;
  return (current.category === candidate.category ? 4 : 0) + (current.audience && current.audience === candidate.audience ? 3 : 0) + sharedTags;
};

export default function ArticlePage() {
  const params = useParams<{ slug: string }>();
  const cmsArticles = usePublicData<CmsArticleRow[]>("/api/public/articles");
  const allArticles = mergeCmsArticles(launchArticles, cmsArticles.data);
  const article = allArticles.find(item => item.slug === params.slug);
  if (!article && cmsArticles.isLoading) return <SiteLayout><main className="grid min-h-[65vh] place-items-center bg-white" id="main-content"><p className="font-bold text-[#4C5566]">Loading article…</p></main></SiteLayout>;
  if (!article) return <NotFound />;
  const service = getWebsiteService(article.relatedService) ?? getWebsiteService("home-loans")!;
  const path = `/learn/${article.slug}`;
  const baseWordCount = words(article.summary) + article.sections.reduce((total,section)=>total+words(section.heading)+words(section.body),0);
  const extraDepth = baseWordCount < 700 ? depthGuidance[article.category] ?? "Before acting, bring the numbers, timing, risks and alternative pathways together in one place. Compare at least two realistic options, not just the first lender or product presented. Stress-test the assumptions and identify which parts require accountant, legal or financial-advice input. Lending policy and market settings change, so current information matters. The aim is to understand what the decision improves, what it costs, what could go wrong and what future options remain after settlement. A finance approval should make the next move possible without unnecessarily closing the one after it." : undefined;
  const relatedArticles = allArticles.filter(candidate => candidate.slug !== article.slug).map(candidate => ({ candidate, score: relationshipScore(article, candidate) })).filter(item => item.score > 0).sort((a,b)=>b.score-a.score).slice(0,3).map(item=>item.candidate);
  const jsonLd = [organizationSchema,{"@context":"https://schema.org","@type":"BlogPosting",headline:article.title,description:article.summary,datePublished:article.publishedAt??"2026-08-18",dateModified:article.updatedAt??article.publishedAt??"2026-08-18",mainEntityOfPage:`${siteUrl}${path}`,inLanguage:"en-AU",articleSection:article.category,keywords:article.tags?.join(", "),author:{"@type":"Person",name:article.authorName??founder.name,url:`${siteUrl}/team/martin-reidy`},publisher:{"@type":"Organization",name:"Next Move Loans",url:siteUrl}},breadcrumbSchema([{name:"Home",path:"/"},{name:"Learning Centre",path:"/learn"},{name:article.title,path}])];

  return <SiteLayout><Seo description={article.summary} jsonLd={jsonLd} path={path} title={`${article.title} | Next Move Loans`} type="article" />
    <main id="main-content" className="bg-white">
      <article>
        <header className="border-b border-[#16203A]/10 py-10 lg:py-12"><div className="container max-w-5xl"><Link className="inline-flex items-center gap-2 text-sm font-black text-[#16203A]" href="/learn"><ArrowLeft className="size-4"/>Learning Centre</Link><p className="mt-7 text-xs font-black uppercase tracking-[0.14em] text-[#EC7354]">{article.category}{article.audience?` · ${article.audience}`:""}</p><h1 className="mt-3 text-[clamp(2.2rem,4vw,4rem)] font-black leading-[1.02] tracking-[-0.045em] text-[#16203A]">{article.title}</h1><p className="mt-4 max-w-4xl text-xl leading-8 text-[#4C5566]">{article.summary}</p><div className="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-sm font-bold text-[#667080]"><span>By {article.authorName??founder.name}</span><span className="inline-flex items-center gap-2"><Clock className="size-4"/>{Math.max(article.readMinutes??7,Math.ceil((baseWordCount+(extraDepth?words(extraDepth):0))/210))} min read</span><span>{displayDate(article.publishedAt)}</span>{article.updatedAt&&article.updatedAt!==article.publishedAt?<span className="inline-flex items-center gap-2"><RefreshCw className="size-4"/>Reviewed {displayDate(article.updatedAt)}</span>:null}</div></div></header>

        <div className="container grid max-w-6xl gap-10 py-10 lg:grid-cols-[0.28fr_0.72fr] lg:py-12">
          <aside className="lg:sticky lg:top-28 lg:self-start"><p className="text-xs font-black uppercase tracking-[0.14em] text-[#EC7354]">RELATED FINANCE</p><h2 className="mt-2 text-xl font-black text-[#16203A]">{service.title}</h2><p className="mt-2 text-sm leading-6 text-[#4C5566]">{service.short}</p><Link className="mt-4 inline-flex items-center gap-2 text-sm font-black text-[#16203A]" href={`/services/${service.slug}`}>Explore options <ArrowRight className="size-4 text-[#EC7354]"/></Link>{article.tags?.length?<div className="mt-8"><p className="text-xs font-black uppercase tracking-[0.14em] text-[#667080]">TOPICS</p><div className="mt-3 flex flex-wrap gap-2">{article.tags.map(tag=><span className="rounded-full bg-[#F3F7FF] px-3 py-1 text-xs font-bold text-[#16203A]" key={tag}>{tag}</span>)}</div></div>:null}</aside>

          <div className="max-w-3xl text-[#354056]">
            {article.sections.map((section,index)=><section className="border-b border-[#16203A]/10 pb-8 pt-2 first:pt-0" key={section.heading}><p className="text-xs font-black text-[#EC7354]">0{index+1}</p><h2 className="mt-2 text-[clamp(1.5rem,2.2vw,2.1rem)] font-black leading-tight tracking-[-0.025em] text-[#16203A]">{section.heading}</h2><p className="mt-4 text-lg leading-8">{section.body}</p></section>)}
            {extraDepth?<section className="border-b border-[#16203A]/10 py-8"><p className="text-xs font-black text-[#EC7354]">CHECKLIST</p><h2 className="mt-2 text-[clamp(1.5rem,2.2vw,2.1rem)] font-black text-[#16203A]">Before you act</h2><p className="mt-4 text-lg leading-8">{extraDepth}</p></section>:null}
            <div className="mt-8 rounded-2xl bg-[#F3F7FF] p-5 text-sm leading-6 text-[#4C5566]"><strong className="text-[#16203A]">Important:</strong> This article is general information only. It does not consider your objectives, financial situation or needs. Lending policy, costs, eligibility, market conditions and government settings can change. Verify current information and seek advice appropriate to your circumstances before acting.</div>
            <Link className="button button-coral mt-7" href="/contact-us">Talk Through the Decision <ArrowRight className="size-4"/></Link>
          </div>
        </div>
      </article>

      {relatedArticles.length?<section className="border-t border-[#16203A]/10 py-9 lg:py-10"><div className="container"><div className="flex items-end justify-between gap-4"><div><Eyebrow>KEEP READING</Eyebrow><h2 className="mt-2 text-2xl font-black text-[#16203A]">Related guides</h2></div><Link className="text-sm font-black text-[#EC7354]" href="/learn">View all →</Link></div><div className="mt-5 grid gap-4 md:grid-cols-3">{relatedArticles.map(related=><Link className="rounded-2xl bg-[#F3F7FF] p-5" href={`/learn/${related.slug}`} key={related.slug}><p className="text-xs font-black uppercase tracking-[0.12em] text-[#EC7354]">{related.category}</p><h3 className="mt-2 text-lg font-black leading-tight text-[#16203A]">{related.title}</h3><span className="mt-4 inline-flex text-sm font-black text-[#16203A]">Read →</span></Link>)}</div></div></section>:null}
    </main>
  </SiteLayout>;
}
