import { useEffect, useState, type FormEvent } from "react";
import { CalendarDays, Mail, MapPin, Phone, Send } from "lucide-react";
import { Seo, breadcrumbSchema } from "@/components/Seo";
import { Eyebrow } from "@/components/Shared";
import { SiteLayout } from "@/components/SiteChrome";
import { contactDetails } from "@/lib/siteData";
import { submitPublicLead } from "@/lib/publicApi";

const moveOptions=["Purchase","Refinance","Investment","Business","Rural / Acreage","Asset Finance","Something else"];

function CalendlyAssets(){useEffect(()=>{if(!document.getElementById("calendly-widget-css")){const l=document.createElement("link");l.id="calendly-widget-css";l.rel="stylesheet";l.href="https://assets.calendly.com/assets/external/widget.css";document.head.appendChild(l);}if(!document.getElementById("calendly-widget-js")){const s=document.createElement("script");s.id="calendly-widget-js";s.src="https://assets.calendly.com/assets/external/widget.js";s.async=true;document.body.appendChild(s);}},[]);return null;}

export default function ContactUs(){
  const[startedAt,setStartedAt]=useState(()=>Date.now());const[reference,setReference]=useState("");const[error,setError]=useState("");const[isSubmitting,setIsSubmitting]=useState(false);
  const onSubmit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError("");setIsSubmitting(true);const form=event.currentTarget;const data=new FormData(form);try{const result=await submitPublicLead({name:String(data.get("name")||""),email:String(data.get("email")||""),mobile:String(data.get("mobile")||""),enquiryType:String(data.get("move")||""),sourcePath:window.location.pathname,website:String(data.get("website")||""),startedAt,message:[`Preferred contact: ${String(data.get("contact")||"Either")}`,`Timing: ${String(data.get("timing")||"Not supplied")}`,"",String(data.get("message")||"")].join("\n").trim()});setReference(result.reference);form.reset();setStartedAt(Date.now());}catch(caught){setError(caught instanceof Error?caught.message:"Your enquiry could not be saved. Please call us instead.");}finally{setIsSubmitting(false);}};
  const openDiscovery=(event:React.MouseEvent<HTMLAnchorElement>)=>{event.preventDefault();const calendly=(window as any).Calendly;if(calendly?.initPopupWidget)calendly.initPopupWidget({url:contactDetails.discoveryCall});else window.open(contactDetails.discoveryCall,"_blank","noopener,noreferrer");};

  return <SiteLayout><CalendlyAssets/><Seo description="Contact Next Move Loans by phone, email or enquiry form, or book a discovery call or Game Plan strategy meeting." jsonLd={breadcrumbSchema([{name:"Home",path:"/"},{name:"Contact Us",path:"/contact-us"}])} path="/contact-us" title="Contact Us | Next Move Loans"/><main id="main-content">
    <section className="bg-[#F7F5F1] py-9 lg:py-11"><div className="container grid gap-8 lg:grid-cols-[0.75fr_1.25fr] lg:items-start"><div><Eyebrow>CONTACT US</Eyebrow><h1 className="mt-3 text-[clamp(2.2rem,4vw,4rem)] font-black leading-[1] tracking-[-0.045em] text-[#16203A]">Start with a conversation.</h1><p className="mt-4 text-lg leading-8 text-[#4C5566]">You do not need to know exactly which loan you need. Tell us what you are trying to do and we will work out the useful next step.</p><div className="mt-6 grid gap-3"><a className="flex items-center gap-3 rounded-xl border border-[#16203A]/10 bg-white p-4" href={contactDetails.landlineHref}><Phone className="size-5 text-[#EC7354]"/><div><p className="text-xs font-black uppercase tracking-[0.12em] text-[#9A6F00]">Call</p><p className="text-xl font-black text-[#16203A]">{contactDetails.landlineDisplay}</p></div></a><a className="flex items-center gap-3 rounded-xl border border-[#16203A]/10 bg-white p-4" href={contactDetails.emailHref}><Mail className="size-5 text-[#EC7354]"/><div><p className="text-xs font-black uppercase tracking-[0.12em] text-[#9A6F00]">Email</p><p className="font-black text-[#16203A]">{contactDetails.email}</p></div></a><div className="flex items-center gap-3 rounded-xl border border-[#16203A]/10 bg-white p-4"><MapPin className="size-5 text-[#EC7354]"/><div><p className="text-xs font-black uppercase tracking-[0.12em] text-[#9A6F00]">Office</p><p className="font-black text-[#16203A]">{contactDetails.address}</p></div></div></div><a className="button button-outline-dark mt-5" href={contactDetails.discoveryCall} onClick={openDiscovery}>Book a Discovery Call <CalendarDays className="size-4"/></a></div>

      <div className="conversion-form-card">{reference?<div className="conversion-preview-state"><span>ENQUIRY SAVED</span><h2>Thanks. We have your starting point.</h2><p>Your reference is <strong>{reference}</strong>. If it is urgent, call {contactDetails.landlineDisplay}.</p><button className="button button-outline-dark" onClick={()=>setReference("")} type="button">Send another enquiry</button></div>:<form onSubmit={onSubmit}><div className="form-heading"><div><p>QUICK ENQUIRY</p><h2>Tell us what you are working on.</h2></div></div><fieldset><legend>What are you working on?</legend><div className="form-choice-grid">{moveOptions.map(option=><label key={option}><input name="move" required type="radio" value={option}/><span>{option}</span></label>)}</div></fieldset><div className="form-grid"><label><span>Name</span><input autoComplete="name" name="name" required/></label><label><span>Email</span><input autoComplete="email" name="email" required type="email"/></label><label><span>Mobile</span><input autoComplete="tel" name="mobile" pattern="[0-9 +()-]{8,}" required type="tel"/></label><label><span>Preferred contact</span><select defaultValue="Either" name="contact"><option>Either</option><option>Phone</option><option>Email</option></select></label><label><span>Timing</span><select defaultValue="Still exploring" name="timing"><option>Now</option><option>Within 3 months</option><option>3–12 months</option><option>Still exploring</option></select></label><label className="form-full"><span>Tell us a little more</span><textarea name="message" placeholder="What are you trying to do? What feels unclear?" rows={4}/></label><label aria-hidden="true" className="form-honeypot"><span>Website</span><input autoComplete="off" name="website" tabIndex={-1}/></label></div><label className="form-consent"><input required type="checkbox"/><span>I agree that Next Move Loans may use these contact details to respond to this enquiry.</span></label>{error?<p className="form-error" role="alert">{error}</p>:null}<button className="button button-coral w-full justify-center" disabled={isSubmitting} type="submit">{isSubmitting?"Sending…":"Send Enquiry"}<Send className="size-4"/></button></form>}</div></div></section>

    <section className="bg-white py-9 lg:py-11"><div className="container"><div className="max-w-3xl"><Eyebrow>GAME PLAN STRATEGY MEETING</Eyebrow><h2 className="mt-2 text-2xl font-black text-[#16203A]">Ready for a deeper strategy conversation?</h2><p className="mt-2 leading-7 text-[#4C5566]">Book a Game Plan session when you are ready to work through your current position, options and next move in more detail.</p></div><div className="calendly-inline-widget mt-5 min-w-[280px]" data-url={contactDetails.gamePlan} style={{height:"680px"}}/></div></section>
  </main></SiteLayout>;
}
