import { Link, useParams } from "wouter";
import { ArrowRight, ArrowUpRight, MapPin, Phone } from "lucide-react";
import { Seo, breadcrumbSchema } from "@/components/Seo";
import { Eyebrow, FaqBlock } from "@/components/Shared";
import { SiteLayout } from "@/components/SiteChrome";
import NotFound from "@/pages/NotFound";
import { contactDetails, getService, siteUrl } from "@/lib/siteData";
import { getLocationSeoPage } from "@/lib/locationData";

export default function LocationPage(){const params=useParams<{slug:string}>();const location=getLocationSeoPage(params.slug);if(!location)return <NotFound/>;const path=`/locations/${location.slug}`;const priorityServices=location.priorityServices.map(slug=>getService(slug)).filter(Boolean);const faqs=[{question:`Can Next Move Loans help me if I am in ${location.title}?`,answer:location.physicalOffice?`Yes. Next Move Loans has a physical office at ${location.officeAddress}, and appointments can also be handled by phone or video.`:`Yes. Next Move Loans works with clients in ${location.title} by phone and video, as well as clients Australia-wide.`},{question:`What type of finance can you help with in ${location.title}?`,answer:"We help with home, investment, self-employed, business, commercial and asset finance, subject to your circumstances and lender policy."},{question:"Do I need to know which lender or product I want?",answer:"No. Start with what you are trying to do, your timing and what feels unclear. The lender and structure come after that."}];const jsonLd=[{"@context":"https://schema.org","@type":"WebPage",name:`Mortgage broker ${location.title}`,url:`${siteUrl}${path}`,about:{"@type":"Place",name:location.title},description:location.intro,keywords:location.keywords.join(", ")},breadcrumbSchema([{name:"Home",path:"/"},{name:"Locations",path:"/locations"},{name:location.title,path}])];return <SiteLayout><Seo description={location.intro} jsonLd={jsonLd} path={path} title={`Mortgage Broker ${location.title} | Home Loans & Finance | Next Move Loans`}/><main id="main-content">
<section className="bg-[#F7F5F1] py-8 lg:py-10"><div className="container grid gap-6 lg:grid-cols-[1fr_0.7fr] lg:items-end"><div><Eyebrow>{location.region}</Eyebrow><h1 className="mt-2 text-[clamp(2.2rem,3.8vw,3.8rem)] font-black tracking-[-0.045em] text-[#16203A]">Mortgage Broker {location.title}</h1><p className="mt-3 max-w-3xl text-lg leading-7 text-[#4C5566]">{location.intro}</p><div className="mt-5 flex flex-wrap gap-3"><Link className="button button-coral" href="/contact-us">Contact Us <ArrowRight className="size-4"/></Link><a className="button button-outline-dark" href={contactDetails.landlineHref}><Phone className="size-4"/>{contactDetails.landlineDisplay}</a></div></div><div className="rounded-xl border border-[#16203A]/10 bg-white p-5"><p className="text-xs font-black uppercase tracking-[0.12em] text-[#9A6F00]">LOCAL CONTEXT</p><p className="mt-2 leading-7 text-[#4C5566]">{location.localAngle}</p>{location.physicalOffice?<p className="mt-3 flex items-center gap-2 font-black text-[#16203A]"><MapPin className="size-4 text-[#EC7354]"/>{location.officeAddress}</p>:null}</div></div></section>

<section className="bg-white py-8 lg:py-10"><div className="container"><div className="flex flex-wrap items-end justify-between gap-4"><div><Eyebrow>{location.title.toUpperCase()} FINANCE QUESTIONS</Eyebrow><h2 className="mt-2 text-2xl font-black text-[#16203A]">What are you trying to solve?</h2></div><Link className="text-sm font-black text-[#EC7354]" href="/contact-us">Ask us →</Link></div><div className="mt-6 grid gap-3 md:grid-cols-2">{priorityServices.map(service=>service?<Link className="group rounded-xl border border-[#16203A]/10 bg-[#F8F7F4] p-5" href={`/services/${service.slug}`} key={service.slug}><p className="text-xs font-black uppercase tracking-[0.12em] text-[#9A6F00]">{service.title}</p><h3 className="mt-2 text-lg font-black leading-tight text-[#16203A]">{service.challenge}</h3><span className="mt-4 inline-flex items-center gap-2 text-sm font-black">See options <ArrowUpRight className="size-4 text-[#EC7354]"/></span></Link>:null)}</div></div></section>

<section className="border-y border-[#16203A]/10 bg-[#F7F5F1] py-8"><div className="container grid gap-6 lg:grid-cols-[0.6fr_1.4fr]"><div><Eyebrow>ABOUT WORKING WITH US</Eyebrow><h2 className="mt-2 text-xl font-black text-[#16203A]">Mortgage and finance help in {location.title}.</h2></div><FaqBlock items={faqs}/></div></section>

<section className="bg-[#16203A] py-6 text-white"><div className="container flex flex-wrap items-center justify-between gap-4"><p className="font-black">In {location.title} or somewhere else in Australia? Start with the question.</p><Link className="button button-coral button-small" href="/contact-us">Start a Conversation</Link></div></section>
</main></SiteLayout>}
