import { Link, useParams } from "wouter";
import { ArrowRight, Check, Phone } from "lucide-react";
import { Seo, breadcrumbSchema, organizationSchema } from "@/components/Seo";
import { Eyebrow, FaqBlock } from "@/components/Shared";
import { SiteLayout } from "@/components/SiteChrome";
import { ReviewProof } from "@/components/ReviewProof";
import NotFound from "@/pages/NotFound";
import { approvalSteps, contactDetails, getCategory, getService, siteUrl } from "@/lib/siteData";

function potentialPath(question:string,serviceTitle:string){const q=question.toLowerCase();if(q.includes("buy before")||q.includes("sell first")||q.includes("sale"))return"Compare sell-first, buy-first and bridging scenarios, including peak debt, buffers and timing.";if(q.includes("rate")||q.includes("switch")||q.includes("cost"))return"Compare the real cost of changing lenders—rate, fees, loan term, cash flow and break-even point.";if(q.includes("term"))return"Model different terms and repayments to see what improves the position, not just the monthly number.";if(q.includes("equity"))return"Test available equity, purpose, loan splits and the impact of the additional debt.";if(q.includes("capacity")||q.includes("borrowing")||q.includes("lender"))return"Compare lender policy, serviceability and sequencing to identify where the real constraint sits.";if(q.includes("valuation")||q.includes("security")||q.includes("classify")||q.includes("land"))return"Check the property and lender policy early, before a valuation or contract deadline creates the problem.";if(q.includes("structure")||q.includes("ownership"))return"Compare available structures and the lending trade-offs, with accountant or adviser input where needed.";if(q.includes("cash")||q.includes("buffer")||q.includes("repayment"))return"Model repayments, buffers and cash flow so the finance supports the move without squeezing everything else.";if(q.includes("document")||q.includes("income")||q.includes("business"))return"Work through how the income is earned, what evidence lenders may use and how to present the position clearly.";return`Compare the lender, structure, timing and trade-offs around ${serviceTitle.toLowerCase()} before you commit.`;}

export default function ServicePage(){const params=useParams<{slug:string}>();const service=getService(params.slug);if(!service)return <NotFound/>;const category=getCategory(service.category)!;const path=`/services/${service.slug}`;const jsonLd=[organizationSchema,{"@context":"https://schema.org","@type":"Service",name:service.title,description:service.short,url:`${siteUrl}${path}`,provider:{"@type":"Organization",name:"Next Move Loans",url:siteUrl},areaServed:"Australia"},breadcrumbSchema([{name:"Home",path:"/"},{name:category.title,path:category.path},{name:service.title,path}])];return <SiteLayout><Seo description={service.short} image={category.image} jsonLd={jsonLd} path={path} title={`${service.title} | Next Move Loans`}/><main id="main-content">
<section className="bg-[#F7F5F1] py-8 lg:py-10"><div className="container grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><Eyebrow>{service.eyebrow}</Eyebrow><h1 className="mt-2 max-w-4xl text-[clamp(2.2rem,3.8vw,3.8rem)] font-black leading-[1] tracking-[-0.045em] text-[#16203A]">{service.title}</h1><p className="mt-3 max-w-3xl text-xl font-black leading-8 text-[#16203A]">{service.challenge}</p></div><div className="flex flex-wrap gap-3"><Link className="button button-coral" href="/contact-us">Contact Us <ArrowRight className="size-4"/></Link><a className="button button-outline-dark" href={contactDetails.landlineHref}><Phone className="size-4"/>{contactDetails.landlineDisplay}</a></div></div></section>

<section className="py-8 lg:py-10"><div className="container"><div className="max-w-3xl"><Eyebrow>QUESTIONS CLIENTS ASK</Eyebrow><h2 className="mt-2 text-[clamp(1.7rem,2.6vw,2.6rem)] font-black tracking-[-0.035em] text-[#16203A]">Start with the question. Then compare the options.</h2></div><div className="mt-6 grid gap-3 lg:grid-cols-3">{service.decisions.map((question,index)=><div className="rounded-xl border border-[#16203A]/10 bg-white p-5" key={question}><span className="text-sm font-black text-[#EC7354]">0{index+1}</span><h3 className="mt-2 text-lg font-black leading-tight text-[#16203A]">{question}</h3><p className="mt-2 text-sm leading-6 text-[#4C5566]">{potentialPath(question,service.title)}</p></div>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-4 rounded-xl bg-[#16203A] px-5 py-4 text-white"><p className="font-semibold">Have a different question about {service.title.toLowerCase()}?</p><Link className="button button-coral button-small" href="/contact-us">Ask Us</Link></div></div></section>

<section className="border-y border-[#16203A]/10 bg-[#F7F5F1] py-8 lg:py-10"><div className="container grid gap-6 lg:grid-cols-[0.62fr_1.38fr]"><div><Eyebrow>WHEN THIS MAY FIT</Eyebrow><h2 className="mt-2 text-2xl font-black text-[#16203A]">Common situations.</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{service.fit.map(item=><div className="flex items-start gap-3 rounded-xl bg-white p-4" key={item}><Check className="mt-1 size-4 shrink-0 text-[#EC7354]"/><p className="font-semibold leading-6 text-[#16203A]">{item}</p></div>)}</div></div></section>

<section className="bg-white py-9 lg:py-11"><div className="container"><div className="text-center"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#B48416]">HOW IT WORKS</p><h2 className="mt-2 text-2xl font-black text-[#16203A]">The Approval Method™</h2><p className="mx-auto mt-2 max-w-2xl text-sm leading-6 text-[#4C5566]">Finance is rarely the goal—it’s the vehicle. Every client starts with the same four steps.</p></div><div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{approvalSteps.map(step=><div key={step.number}><span className="text-sm font-black text-[#EC7354]">{step.number}</span><h3 className="mt-2 text-lg font-black text-[#16203A]">{step.title}</h3><p className="mt-2 text-sm leading-6 text-[#4C5566]">{step.short}</p></div>)}</div><div className="mt-6 text-center"><Link className="font-black text-[#16203A] underline decoration-[#EC7354] underline-offset-4" href="/approval-method">See the full method</Link></div></div></section>

<ReviewProof compact placement="services"/>

<section className="bg-[#F7F5F1] py-8 lg:py-10"><div className="container grid gap-6 lg:grid-cols-[0.65fr_1.35fr]"><div><Eyebrow>COMMON QUESTIONS</Eyebrow><h2 className="mt-2 text-2xl font-black text-[#16203A]">A few practical answers.</h2></div><FaqBlock items={service.faq}/></div></section>

<section className="bg-[#16203A] py-7 text-white"><div className="container flex flex-wrap items-center justify-between gap-5"><h2 className="text-xl font-black">Talk through the question before you commit to the loan.</h2><div className="flex flex-wrap gap-3"><Link className="button button-coral" href="/contact-us">Contact Us</Link><Link className="button button-outline-light" href="/book-a-call">Book a Call</Link></div></div></section>
</main></SiteLayout>}
