import { useState } from "react";
import { Plus, Save } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { AdminPanel, AdminScreen, EmptyState, Field } from "./AdminUi";

const blank = { id: undefined as number | undefined, settingKey: "", valueType: "text" as "text" | "json" | "boolean" | "number", value: "", settingGroup: "public" };

export default function AdminSettings() {
  const utils = trpc.useUtils(); const settings = trpc.adminCms.settings.useQuery(); const [form, setForm] = useState(blank); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const save = trpc.adminCms.saveSetting.useMutation({ onSuccess: async row => { await Promise.all([utils.adminCms.settings.invalidate(), utils.publicContent.settings.invalidate()]); setForm(current => ({ ...current, id: row.id })); setMessage(`Saved ${row.settingKey}.`); } });
  const edit = (row: NonNullable<typeof settings.data>[number]) => setForm({ id: row.id, settingKey: row.settingKey, valueType: row.valueType, value: row.valueType === "json" ? JSON.stringify(row.valueJson ?? {}, null, 2) : row.valueText ?? "", settingGroup: row.settingGroup });
  const submit = () => { setError(""); let valueJson: Record<string, unknown> | unknown[] | null = null; if (form.valueType === "json") { try { valueJson = JSON.parse(form.value); } catch { return setError("JSON settings must contain valid JSON."); } } save.mutate({ id: form.id, settingKey: form.settingKey, valueType: form.valueType, valueText: form.valueType === "json" ? null : form.value, valueJson, settingGroup: form.settingGroup }); };
  return <AdminScreen eyebrow="CENTRAL CONFIGURATION" title="Website settings" intro="Keep public contact details and non-secret marketing IDs visible in structured configuration. Credentials and provider secrets belong in the secure environment, never here." actions={<button className="admin-button admin-button-secondary" onClick={() => { setForm(blank); setMessage(""); setError(""); }}><Plus /> New setting</button>}>
    <div className="admin-notice"><div><strong>Non-secret values only.</strong><p>GA4 measurement IDs, GTM container IDs, public phone numbers and call-tracking flags can live here. API keys, email credentials and OAuth secrets must use secure environment variables.</p></div></div>
    <div className="admin-editor-layout"><AdminPanel title="Stored settings" intro="Groups make contact, analytics, review and public configuration easy to export." className="admin-record-list-panel">{settings.data?.length ? <div className="admin-record-list">{settings.data.map(row => <button className={form.id === row.id ? "is-active" : ""} onClick={() => edit(row)} key={row.id}><div><strong>{row.settingKey}</strong><span>{row.settingGroup} · {row.valueType}</span></div></button>)}</div> : <EmptyState>No settings.</EmptyState>}</AdminPanel>
      <AdminPanel title={form.id ? "Edit setting" : "New setting"} intro="Use stable, descriptive keys such as analytics.ga4MeasurementId or contact.primaryPhone."><div className="admin-form-grid"><Field label="Setting key"><input value={form.settingKey} onChange={event => setForm({ ...form, settingKey: event.target.value })} /></Field><Field label="Group"><input value={form.settingGroup} onChange={event => setForm({ ...form, settingGroup: event.target.value })} /></Field><Field label="Value type"><select value={form.valueType} onChange={event => setForm({ ...form, valueType: event.target.value as typeof form.valueType })}><option value="text">text</option><option value="json">json</option><option value="boolean">boolean</option><option value="number">number</option></select></Field><Field label="Value" full>{form.valueType === "json" ? <textarea className="admin-code-field" rows={10} value={form.value} onChange={event => setForm({ ...form, value: event.target.value })} /> : <input value={form.value} onChange={event => setForm({ ...form, value: event.target.value })} />}</Field></div>{error ? <p className="admin-alert admin-alert-error">{error}</p> : null}{save.error ? <p className="admin-alert admin-alert-error">{save.error.message}</p> : null}{message ? <p className="admin-alert admin-alert-success">{message}</p> : null}<button className="admin-button admin-button-primary mt-6" disabled={save.isPending} onClick={submit}><Save /> {save.isPending ? "Saving…" : "Save setting"}</button></AdminPanel></div>
  </AdminScreen>;
}

