import { useState } from "react";
import { Plus, Save } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { AdminPanel, AdminScreen, EmptyState, Field, StatusPill } from "./AdminUi";

const blank = { id: undefined as number | undefined, stableKey: "", label: "", blockType: "cta", schemaVersion: "1", payloadText: "{}", status: "draft" as "draft" | "published" | "unpublished", placements: "" };

export default function AdminBlocks() {
  const utils = trpc.useUtils(); const blocks = trpc.adminCms.blocks.useQuery(); const [form, setForm] = useState(blank); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const save = trpc.adminCms.saveBlock.useMutation({ onSuccess: async row => { await utils.adminCms.blocks.invalidate(); setForm(current => ({ ...current, id: row.id })); setMessage(`Saved ${row.label}.`); } });
  const edit = (row: NonNullable<typeof blocks.data>[number]) => setForm({ id: row.id, stableKey: row.stableKey, label: row.label, blockType: row.blockType, schemaVersion: String(row.schemaVersion), payloadText: JSON.stringify(row.payload, null, 2), status: row.status, placements: row.placements.join(", ") });
  const submit = () => { setError(""); try { const payload = JSON.parse(form.payloadText); if (!payload || Array.isArray(payload) || typeof payload !== "object") throw new Error("Payload must be a JSON object."); save.mutate({ id: form.id, stableKey: form.stableKey, label: form.label, blockType: form.blockType, schemaVersion: Number(form.schemaVersion), payload, status: form.status, placements: form.placements.split(",").map(item => item.trim()).filter(Boolean) }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Invalid payload."); } };
  return <AdminScreen eyebrow="REUSABLE CONTENT" title="Content blocks" intro="Store CTAs, trust notices, contact panels, disclosures and repeatable copy once, then reference them by stable key across public templates." actions={<button className="admin-button admin-button-secondary" onClick={() => { setForm(blank); setMessage(""); setError(""); }}><Plus /> New block</button>}>
    <div className="admin-editor-layout"><AdminPanel title="Reusable blocks" intro="Stable keys remain unchanged when the display label or copy changes." className="admin-record-list-panel">{blocks.data?.length ? <div className="admin-record-list">{blocks.data.map(row => <button className={form.id === row.id ? "is-active" : ""} key={row.id} onClick={() => edit(row)}><div><strong>{row.label}</strong><span>{row.stableKey} · {row.blockType}</span></div><StatusPill status={row.status} /></button>)}</div> : <EmptyState>No reusable blocks yet.</EmptyState>}</AdminPanel>
      <AdminPanel title={form.id ? "Edit content block" : "New content block"} intro="The payload is explicit JSON so it can be validated, exported and migrated without scraping rendered HTML."><div className="admin-form-grid"><Field label="Stable key"><input value={form.stableKey} onChange={event => setForm({ ...form, stableKey: event.target.value.toLowerCase().replace(/[^a-z0-9._-]/g, "-") })} /></Field><Field label="Display label"><input value={form.label} onChange={event => setForm({ ...form, label: event.target.value })} /></Field><Field label="Block type"><input value={form.blockType} onChange={event => setForm({ ...form, blockType: event.target.value })} /></Field><Field label="Schema version"><input min="1" type="number" value={form.schemaVersion} onChange={event => setForm({ ...form, schemaVersion: event.target.value })} /></Field><Field label="Status"><select value={form.status} onChange={event => setForm({ ...form, status: event.target.value as typeof form.status })}><option value="draft">draft</option><option value="published">published</option><option value="unpublished">unpublished</option></select></Field><Field label="Placements"><input value={form.placements} onChange={event => setForm({ ...form, placements: event.target.value })} /></Field><Field label="Payload JSON" full><textarea className="admin-code-field" rows={16} value={form.payloadText} onChange={event => setForm({ ...form, payloadText: event.target.value })} /></Field></div>{error ? <p className="admin-alert admin-alert-error">{error}</p> : null}{save.error ? <p className="admin-alert admin-alert-error">{save.error.message}</p> : null}{message ? <p className="admin-alert admin-alert-success">{message}</p> : null}<button className="admin-button admin-button-primary mt-6" disabled={save.isPending} onClick={submit}><Save /> {save.isPending ? "Saving…" : "Save block"}</button></AdminPanel></div>
  </AdminScreen>;
}
