import { type ChangeEvent, useState } from "react";
import { ImageUp, Upload } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { AdminPanel, AdminScreen, EmptyState, Field, formatAdminDate } from "./AdminUi";

export default function AdminMedia() {
  const utils = trpc.useUtils(); const media = trpc.adminCms.media.useQuery();
  const [file, setFile] = useState<File | null>(null); const [altText, setAltText] = useState(""); const [caption, setCaption] = useState(""); const [credit, setCredit] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const upload = trpc.adminCms.uploadMedia.useMutation({ onSuccess: async row => { await utils.adminCms.media.invalidate(); setFile(null); setAltText(""); setCaption(""); setCredit(""); setMessage(`Uploaded ${row.originalFilename}.`); } });
  const choose = (event: ChangeEvent<HTMLInputElement>) => { const next = event.target.files?.[0] ?? null; setError(""); setMessage(""); if (next && next.size > 5_000_000) { setError("Files must be 5 MB or smaller."); setFile(null); return; } setFile(next); };
  const submit = async () => { setError(""); if (!file) return setError("Choose a file first."); if (file.type.startsWith("image/") && !altText.trim()) return setError("Meaningful alternative text is required for public images."); try { const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("The file could not be read.")); reader.readAsDataURL(file); }); const contentBase64 = dataUrl.split(",")[1]; if (!contentBase64) throw new Error("The file could not be encoded."); await upload.mutateAsync({ fileName: file.name, mimeType: file.type as "image/jpeg" | "image/png" | "image/webp" | "image/svg+xml" | "application/pdf", contentBase64, altText: altText.trim() || null, caption: caption.trim() || null, credit: credit.trim() || null }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Upload failed."); } };
  return <AdminScreen eyebrow="MANAGED STORAGE" title="Media library" intro="File bytes live in managed object storage; the database keeps portable URLs, storage keys, filenames, accessibility text, captions and credits.">
    <AdminPanel title="Upload media" intro="Accepted: JPEG, PNG, WebP, SVG and PDF. Maximum 5 MB. Optimise large photography before upload."><div className="admin-form-grid"><Field label="File" hint="Do not upload client identification, financial documents or other sensitive records."><input accept="image/jpeg,image/png,image/webp,image/svg+xml,application/pdf" onChange={choose} type="file" /></Field><Field label="Alternative text" hint="Describe the purpose of the image; leave empty only for a PDF."><input value={altText} onChange={event => setAltText(event.target.value)} /></Field><Field label="Caption"><input value={caption} onChange={event => setCaption(event.target.value)} /></Field><Field label="Credit"><input value={credit} onChange={event => setCredit(event.target.value)} /></Field></div>{file ? <p className="admin-file-selection"><ImageUp /> {file.name} · {(file.size / 1024).toFixed(0)} KB</p> : null}{error ? <p className="admin-alert admin-alert-error">{error}</p> : null}{upload.error ? <p className="admin-alert admin-alert-error">{upload.error.message}</p> : null}{message ? <p className="admin-alert admin-alert-success">{message}</p> : null}<button className="admin-button admin-button-primary mt-6" disabled={!file || upload.isPending} onClick={submit}><Upload /> {upload.isPending ? "Uploading…" : "Upload to media library"}</button></AdminPanel>
    <AdminPanel title="Stored media" intro="The export manifest includes every record below so media can be retrieved and remapped during a future migration.">{media.data?.length ? <div className="admin-media-grid">{media.data.map(item => <article key={item.id}>{item.mimeType.startsWith("image/") ? <img alt={item.altText || ""} src={item.publicUrl} /> : <div className="admin-pdf-tile">PDF</div>}<div><strong>{item.originalFilename}</strong><span>{item.mimeType} · {formatAdminDate(item.createdAt)}</span><p>{item.altText || "No alternative text recorded"}</p><a href={item.publicUrl} rel="noreferrer" target="_blank">Open stored file</a></div></article>)}</div> : <EmptyState>No media records.</EmptyState>}</AdminPanel>
  </AdminScreen>;
}

