/** Clean consumer navigation: Game Plan, About, Finance, Learn, Contact. */
import { useEffect, useState, type ReactNode } from "react";
import { Link, useLocation } from "wouter";
import { ArrowUpRight, ChevronDown, Menu, Phone, X } from "lucide-react";
import { contactDetails } from "@/lib/siteData";

const financeLinks = [
  ["Home & Property", "/finance/home-property"],
  ["Investment", "/finance/investment"],
  ["Business & Commercial", "/finance/business-commercial"],
  ["Asset Finance", "/finance/asset"],
  ["All Loan Types", "/loan-types"],
] as const;
const activeClass = "text-[#EC7354]";

function BrandMark({ reversed = false }: { reversed?: boolean }) {
  return <img alt="Next Move Loans" className={reversed ? "h-auto w-[220px]" : "h-auto w-[190px] md:w-[215px]"} decoding="async" src={reversed ? "/brand/next-move-loans-reversed.svg" : "/brand/next-move-loans.svg"} />;
}
function Dropdown({ label, links, location }: { label: string; links: readonly (readonly [string, string])[]; location: string }) {
  const active = links.some(([, href]) => location.startsWith(href));
  return <div className="group relative"><button className={`nav-trigger ${active ? activeClass : ""}`} type="button">{label}<ChevronDown className="size-3.5" /></button><div className="nav-flyout invisible absolute left-0 top-full z-50 min-w-72 translate-y-2 opacity-0 group-hover:visible group-hover:translate-y-0 group-hover:opacity-100 group-focus-within:visible group-focus-within:translate-y-0 group-focus-within:opacity-100">{links.map(([text,href])=><Link className="nav-flyout-link" href={href} key={href}><span>{text}</span><ArrowUpRight className="size-4 text-[#EC7354]"/></Link>)}</div></div>;
}
function DesktopNavigation({ location }: { location: string }) { return <nav aria-label="Primary navigation" className="hidden items-center gap-1 lg:flex"><Link className={`nav-trigger ${location.startsWith("/game-plan") || location.startsWith("/approval-method") ? activeClass : ""}`} href="/game-plan">The Game Plan</Link><Link className={`nav-trigger ${location.startsWith("/about") ? activeClass : ""}`} href="/about">About Us</Link><Dropdown label="Finance" links={financeLinks} location={location}/><Link className={`nav-trigger ${location.startsWith("/learn") ? activeClass : ""}`} href="/learn">Learn</Link></nav>; }
function MobileNavigation({ open, close }: { open: boolean; close: () => void }) {
  if (!open) return null;
  return <div className="mobile-nav-panel lg:hidden"><nav aria-label="Mobile navigation" className="container py-6"><div className="grid gap-2"><Link className="mobile-nav-link" href="/game-plan" onClick={close}>The Game Plan</Link><Link className="mobile-nav-link" href="/about" onClick={close}>About Us</Link><Link className="mobile-nav-link" href="/learn" onClick={close}>Learn</Link></div><p className="mb-2 mt-6 text-xs font-semibold uppercase tracking-[0.18em] text-[#C3A342]">Finance</p><div className="grid gap-1">{financeLinks.map(([label,href])=><Link className="mobile-nav-link" href={href} key={href} onClick={close}>{label}<ArrowUpRight className="size-4"/></Link>)}</div><a className="mt-6 inline-flex items-center gap-2 text-lg font-black text-white" href={contactDetails.landlineHref}><Phone className="size-5 text-[#EC7354]"/>{contactDetails.landlineDisplay}</a><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link className="button button-coral" href="/contact-us" onClick={close}>Contact Us</Link><Link className="button button-outline-light" href="/book-a-call" onClick={close}>Book a Call</Link></div></nav></div>;
}
export function Header() {
  const [location] = useLocation(); const [open,setOpen]=useState(false); const [scrolled,setScrolled]=useState(false);
  useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>12);onScroll();window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll);},[]);
  useEffect(()=>setOpen(false),[location]);
  return <header className={`site-header ${scrolled ? "site-header-scrolled" : ""}`} style={{background:"rgba(255,255,255,.98)"}}><div className="container flex h-[4.7rem] items-center justify-between gap-5"><Link aria-label="Next Move Loans home" className="shrink-0" href="/"><BrandMark/></Link><DesktopNavigation location={location}/><div className="hidden items-center gap-3 lg:flex"><a className="inline-flex items-center gap-2 font-black text-[#16203A]" href={contactDetails.landlineHref}><Phone className="size-4 text-[#EC7354]"/>{contactDetails.landlineDisplay}</a><Link className="text-link" href="/book-a-call">Book a Call</Link><Link className="button button-coral button-small" href="/contact-us">Contact Us</Link></div><button aria-expanded={open} aria-label={open?"Close menu":"Open menu"} className="menu-button lg:hidden" onClick={()=>setOpen(v=>!v)} type="button">{open?<X/>:<Menu/>}</button></div><MobileNavigation close={()=>setOpen(false)} open={open}/></header>;
}
export function Footer(){return <footer className="bg-[#16203A] text-white"><div className="container py-12"><div className="grid gap-9 border-b border-white/15 pb-10 lg:grid-cols-[1.05fr_1.95fr]"><div><BrandMark reversed/><p className="mt-5 max-w-sm text-lg font-black leading-7">Everyone’s building something. We unlock the path.</p><a className="mt-5 inline-flex items-center gap-2 text-xl font-black" href={contactDetails.landlineHref}><Phone className="size-5 text-[#EC7354]"/>{contactDetails.landlineDisplay}</a></div><div className="grid gap-7 sm:grid-cols-3"><div><p className="footer-heading">Next Move</p><div className="grid gap-2.5"><Link className="footer-link" href="/game-plan">The Game Plan</Link><Link className="footer-link" href="/about">About Us</Link><Link className="footer-link" href="/learn">Learning Centre</Link><Link className="footer-link" href="/locations">Locations</Link><Link className="footer-link" href="/for-brokers">For Brokers</Link></div></div><div><p className="footer-heading">Finance</p><div className="grid gap-2.5">{financeLinks.map(([label,href])=><Link className="footer-link" href={href} key={href}>{label}</Link>)}</div></div><div><p className="footer-heading">Contact</p><div className="grid gap-2.5"><a className="footer-link" href={contactDetails.emailHref}>{contactDetails.email}</a><span className="text-sm leading-6 text-white/55">{contactDetails.address}</span><Link className="footer-link" href="/contact-us">Contact Us</Link><Link className="footer-link" href="/important-information">Important Information</Link><Link className="footer-link" href="/privacy">Privacy</Link></div></div></div></div><div className="pt-6 text-sm text-white/55">© {new Date().getFullYear()} Next Move Loans.</div></div></footer>}
export function SiteLayout({children}:{children:ReactNode}){const[location]=useLocation();useEffect(()=>{window.scrollTo({top:0,behavior:"instant"});},[location]);return <div className="min-h-screen overflow-clip bg-white text-[#16203A]"><a className="skip-link" href="#main-content">Skip to main content</a><Header/>{children}<Footer/><div className="mobile-action-bar lg:hidden"><Link className="mobile-action-primary" href="/contact-us">Contact Us</Link><a className="mobile-action-secondary" href={contactDetails.landlineHref}><Phone className="size-4"/>Call</a></div></div>}
